CIRCT: circt::firrtl::FIRRTLDialect Class Reference
circt::firrtl::FIRRTLDialect Class Reference
#include <FIRRTLDialect.h>
Public Member Functions
FIRRTLDialect (MLIRContext *context)
Create the dialect in the given context.
~FIRRTLDialect ()
Type parseType (DialectAsmParser &parser) const override
Parse a type registered to this dialect.
void printType (Type, DialectAsmPrinter &) const override
Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc) override
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
Static Public Member Functions
static StringRef getDialectNamespace ()
Detailed Description
Definition at line 24 of file FIRRTLDialect.h.
Constructor & Destructor Documentation
FIRRTLDialect()
FIRRTLDialect::FIRRTLDialect (MLIRContext * context) explicit
Create the dialect in the given context.
Definition at line 125 of file FIRRTLDialect.cpp.
~FIRRTLDialect()
FIRRTLDialect::~FIRRTLDialect ()
Definition at line 144 of file FIRRTLDialect.cpp.
Member Function Documentation
getDialectNamespace()
static StringRef circt::firrtl::FIRRTLDialect::getDialectNamespace () inline static
Definition at line 36 of file FIRRTLDialect.h.
References circt::firrtl::getFIRRTLNameAttr().
materializeConstant()
Operation * FIRRTLDialect::materializeConstant (OpBuilder & builder, Attribute value, Type type, Location loc) override
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
This method should use the provided builder to create the operation without changing the insertion position. The generated operation is expected to be constant like, i.e. single result, zero operands, non side-effecting, etc. On success, this hook should return the value generated to represent the constant value. Otherwise, it should return null on failure.
Definition at line 157 of file FIRRTLDialect.cpp.
parseType()
Type FIRRTLDialect::parseType (DialectAsmParser & parser) const override
Parse a type registered to this dialect.
Definition at line 185 of file FIRRTLTypes.cpp.
References parseType().
printType()
void FIRRTLDialect::printType (Type type, DialectAsmPrinter & os) const override
Definition at line 146 of file FIRRTLDialect.cpp.
References print().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLDialect.h
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp