CIRCT: circt::firrtl::FlipType Class Reference
circt::firrtl::FlipType Class Reference
#include <FIRRTLTypes.h>
Public Member Functions
FIRRTLType getElementType ()
Static Public Member Functions
static FIRRTLType get (FIRRTLType element)
Detailed Description
Definition at line 214 of file FIRRTLTypes.h.
Member Function Documentation
get()
FIRRTLType FlipType::get (FIRRTLType element) static
Definition at line 510 of file FIRRTLTypes.cpp.
References circt::firrtl::FVectorType::get(), circt::firrtl::BundleType::getElements(), getElementType(), circt::firrtl::FVectorType::getElementType(), getFlippedBundleType(), circt::firrtl::FVectorType::getNumElements(), circt::firrtl::BundleType::getRecursiveTypeProperties(), and circt::firrtl::FVectorType::getRecursiveTypeProperties().
Referenced by circt::firrtl::createLowerFIRRTLTypesPass(), circt::firrtl::BundleType::get(), circt::firrtl::FVectorType::get(), getFlippedBundleType(), circt::firrtl::FIRRTLType::getMaskType(), circt::firrtl::FIRRTLType::getWidthlessType(), tryEliminatingConnectsToValue(), verifyConstantOp(), and verifyInstanceOp().
getElementType()
FIRRTLType FlipType::getElementType ()
Definition at line 563 of file FIRRTLTypes.cpp.
Referenced by get(), getBitWidthOrSentinel(), circt::firrtl::FIRRTLType::getMaskType(), circt::firrtl::FIRRTLType::getPassiveType(), getSignednessOf(), circt::firrtl::FIRRTLType::getWidthlessType(), and circt::firrtl::FIRRTLType::print().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp