CIRCT: circt::ImplicitLocOpBuilder Class Reference
circt::ImplicitLocOpBuilder Class Reference
ImplictLocOpBuilder maintains a 'current location', allowing use of the create<> method without specifying the location.
#include <ImplicitLocOpBuilder.h>
Public Member Functions
ImplicitLocOpBuilder (Location loc, const OpBuilder &builder)
Create an ImplicitLocOpBuilder using the insertion point and listener from an existing OpBuilder.
template<typename T >
ImplicitLocOpBuilder (Location loc, T &&operand, Listener *listener=nullptr)
OpBuilder has a bunch of convenience constructors - we support them all with the additional Location.
ImplicitLocOpBuilder (Location loc, Block *block, Block::iterator insertPoint, Listener *listener=nullptr)
ImplicitLocOpBuilder (mlir::Operation *op)
Location getLoc () const
Accessors for the implied location.
void setLoc (Location loc)
template<typename OpTy , typename... Args>
OpTy create (Args &&... args)
Create an operation of specific op type at the current insertion point and location.
template<typename OpTy , typename... Args>
void createOrFold (llvm::SmallVectorImpl< Value > &results, Args &&... args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< mlir::OpTrait::OneResult >), Value >::type createOrFold (Args &&... args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< mlir::OpTrait::ZeroResult >), OpTy >::type createOrFold (Args &&... args)
Overload to create or fold a zero result operation.
mlir::InFlightDiagnostic emitError (const llvm::Twine &message=llvm::Twine())
This builder can also be used to emit diagnostics to the current location.
mlir::InFlightDiagnostic emitWarning (const llvm::Twine &message=llvm::Twine())
mlir::InFlightDiagnostic emitRemark (const llvm::Twine &message=llvm::Twine())
Static Public Member Functions
static ImplicitLocOpBuilder atBlockBegin (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static ImplicitLocOpBuilder atBlockEnd (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static ImplicitLocOpBuilder atBlockTerminator (Location loc, Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Private Types
using OpBuilder = mlir::OpBuilder
using Location = mlir::Location
using Block = mlir::Block
using Value = mlir::Value
Private Attributes
Location curLoc
Detailed Description
ImplictLocOpBuilder maintains a 'current location', allowing use of the create<> method without specifying the location.
It is otherwise the same as OpBuilder.
Definition at line 23 of file ImplicitLocOpBuilder.h.
Member Typedef Documentation
Block
using circt::ImplicitLocOpBuilder::Block = mlir::Block private
Definition at line 26 of file ImplicitLocOpBuilder.h.
Location
using circt::ImplicitLocOpBuilder::Location = mlir::Location private
Definition at line 25 of file ImplicitLocOpBuilder.h.
OpBuilder
using circt::ImplicitLocOpBuilder::OpBuilder = mlir::OpBuilder private
Definition at line 24 of file ImplicitLocOpBuilder.h.
Value
using circt::ImplicitLocOpBuilder::Value = mlir::Value private
Definition at line 27 of file ImplicitLocOpBuilder.h.
Constructor & Destructor Documentation
ImplicitLocOpBuilder() [1/4]
circt::ImplicitLocOpBuilder::ImplicitLocOpBuilder (Location loc, const OpBuilder & builder) inline
Create an ImplicitLocOpBuilder using the insertion point and listener from an existing OpBuilder.
Definition at line 32 of file ImplicitLocOpBuilder.h.
Referenced by atBlockBegin(), atBlockEnd(), and atBlockTerminator().
ImplicitLocOpBuilder() [2/4]
template<typename T > circt::ImplicitLocOpBuilder::ImplicitLocOpBuilder (Location loc, T && operand, Listener * listener = nullptr) inline
OpBuilder has a bunch of convenience constructors - we support them all with the additional Location.
Definition at line 38 of file ImplicitLocOpBuilder.h.
ImplicitLocOpBuilder() [3/4]
circt::ImplicitLocOpBuilder::ImplicitLocOpBuilder (Location loc, Block * block, Block::iterator insertPoint, Listener * listener = nullptr) inline
Definition at line 41 of file ImplicitLocOpBuilder.h.
ImplicitLocOpBuilder() [4/4]
circt::ImplicitLocOpBuilder::ImplicitLocOpBuilder (mlir::Operation * op) inline
Definition at line 44 of file ImplicitLocOpBuilder.h.
Member Function Documentation
atBlockBegin()
static ImplicitLocOpBuilder circt::ImplicitLocOpBuilder::atBlockBegin (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
Definition at line 49 of file ImplicitLocOpBuilder.h.
References ImplicitLocOpBuilder().
atBlockEnd()
static ImplicitLocOpBuilder circt::ImplicitLocOpBuilder::atBlockEnd (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
Definition at line 56 of file ImplicitLocOpBuilder.h.
References ImplicitLocOpBuilder().
atBlockTerminator()
static ImplicitLocOpBuilder circt::ImplicitLocOpBuilder::atBlockTerminator (Location loc, Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the block terminator.
Definition at line 63 of file ImplicitLocOpBuilder.h.
References ImplicitLocOpBuilder().
create()
template<typename OpTy , typename... Args> OpTy circt::ImplicitLocOpBuilder::create (Args &&... args) inline
Create an operation of specific op type at the current insertion point and location.
Definition at line 82 of file ImplicitLocOpBuilder.h.
References curLoc.
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass(), and tryEliminatingConnectsToValue().
createOrFold() [1/3]
template<typename OpTy , typename... Args> void circt::ImplicitLocOpBuilder::createOrFold (llvm::SmallVectorImpl< Value > & results, Args &&... args) inline
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
This functions populates 'results' with the results after folding the operation.
Definition at line 90 of file ImplicitLocOpBuilder.h.
References curLoc.
Referenced by castFromFIRRTLType(), castToFIRRTLType(), and tryEliminatingConnectsToValue().
createOrFold() [2/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<mlir::OpTrait::OneResult>), Value>::type circt::ImplicitLocOpBuilder::createOrFold (Args &&... args) inline
Overload to create or fold a single result operation.
Definition at line 98 of file ImplicitLocOpBuilder.h.
References curLoc.
createOrFold() [3/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<mlir::OpTrait::ZeroResult>), OpTy>::type circt::ImplicitLocOpBuilder::createOrFold (Args &&... args) inline
Overload to create or fold a zero result operation.
Definition at line 106 of file ImplicitLocOpBuilder.h.
References curLoc.
emitError()
mlir::InFlightDiagnostic circt::ImplicitLocOpBuilder::emitError (const llvm::Twine & message = llvm::Twine()) inline
This builder can also be used to emit diagnostics to the current location.
Definition at line 112 of file ImplicitLocOpBuilder.h.
References curLoc.
emitRemark()
mlir::InFlightDiagnostic circt::ImplicitLocOpBuilder::emitRemark (const llvm::Twine & message = llvm::Twine()) inline
Definition at line 120 of file ImplicitLocOpBuilder.h.
References curLoc.
emitWarning()
mlir::InFlightDiagnostic circt::ImplicitLocOpBuilder::emitWarning (const llvm::Twine & message = llvm::Twine()) inline
Definition at line 116 of file ImplicitLocOpBuilder.h.
References curLoc.
getLoc()
Location circt::ImplicitLocOpBuilder::getLoc () const inline
Accessors for the implied location.
Definition at line 72 of file ImplicitLocOpBuilder.h.
References curLoc.
setLoc()
void circt::ImplicitLocOpBuilder::setLoc (Location loc) inline
Definition at line 73 of file ImplicitLocOpBuilder.h.
References curLoc.
Referenced by circt::firrtl::createLowerFIRRTLToRTLPass().
Member Data Documentation
curLoc
Location circt::ImplicitLocOpBuilder::curLoc private
Definition at line 125 of file ImplicitLocOpBuilder.h.
Referenced by create(), createOrFold(), emitError(), emitRemark(), emitWarning(), getLoc(), and setLoc().
The documentation for this class was generated from the following file:
include/circt/Support/ImplicitLocOpBuilder.h