CIRCT: circt::firrtl::BundleType Class Reference
circt::firrtl::BundleType Class Reference
BundleType is an aggregate of named elements.
#include <FIRRTLTypes.h>
Classes
struct BundleElement
Public Member Functions
ArrayRef< BundleElement > getElements ()
size_t getNumElements ()
llvm::Optional< BundleElement > getElement (StringRef name)
Look up an element by name. This returns None on failure.
FIRRTLType getElementType (StringRef name)
std::pair< bool, bool > getRecursiveTypeProperties ()
Return a pair with the 'isPassive' and 'containsAnalog' bits.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
Static Public Member Functions
static FIRRTLType get (ArrayRef< BundleElement > elements, MLIRContext *context)
Detailed Description
BundleType is an aggregate of named elements.
This is effectively a struct for FIRRTL.
Definition at line 230 of file FIRRTLTypes.h.
Member Function Documentation
get()
FIRRTLType BundleType::get (ArrayRef< BundleElement > elements, MLIRContext * context) static
Definition at line 630 of file FIRRTLTypes.cpp.
References circt::firrtl::FlipType::get(), getFlippedBundleType(), and circt::firrtl::BundleType::BundleElement::type.
Referenced by getFlippedBundleType(), circt::firrtl::FIRRTLType::getMaskType(), getPassiveType(), circt::firrtl::FIRRTLType::getWidthlessType(), parseType(), and verifyInstanceOp().
getElement()
auto BundleType::getElement (StringRef name)
Look up an element by name. This returns None on failure.
Look up an element by name. This returns a BundleElement with.
Definition at line 682 of file FIRRTLTypes.cpp.
getElements()
auto BundleType::getElements ()
Definition at line 644 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::areTypesEquivalent(), circt::firrtl::createLowerFIRRTLTypesPass(), circt::firrtl::FlipType::get(), circt::firrtl::FIRRTLType::getMaskType(), and verifyRTLStructCastOp().
getElementType()
FIRRTLType BundleType::getElementType (StringRef name)
Definition at line 690 of file FIRRTLTypes.cpp.
Referenced by getCanonicalBundleType(), and getMemPortKindFromType().
getNumElements()
size_t circt::firrtl::BundleType::getNumElements () inline
Definition at line 252 of file FIRRTLTypes.h.
References circt::firrtl::getPassiveType().
getPassiveType()
FIRRTLType BundleType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 656 of file FIRRTLTypes.cpp.
References get(), and IsPassiveBitMask.
Referenced by circt::firrtl::FIRRTLType::getPassiveType().
getRecursiveTypeProperties()
std::pair< bool, bool > BundleType::getRecursiveTypeProperties ()
Return a pair with the 'isPassive' and 'containsAnalog' bits.
Definition at line 649 of file FIRRTLTypes.cpp.
References ContainsAnalogBitMask, and IsPassiveBitMask.
Referenced by circt::firrtl::FlipType::get(), and circt::firrtl::FIRRTLType::getRecursiveTypeProperties().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp