CIRCT: circt::firrtl::FVectorType Class Reference
circt::firrtl::FVectorType Class Reference
VectorType is a fixed size collection of elements, like an array.
#include <FIRRTLTypes.h>
Public Member Functions
FIRRTLType getElementType ()
unsigned getNumElements ()
std::pair< bool, bool > getRecursiveTypeProperties ()
Return a pair with the 'isPassive' and 'containsAnalog' bits.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
Static Public Member Functions
static FIRRTLType get (FIRRTLType elementType, unsigned numElements)
Detailed Description
VectorType is a fixed size collection of elements, like an array.
Definition at line 270 of file FIRRTLTypes.h.
Member Function Documentation
get()
FIRRTLType FVectorType::get (FIRRTLType elementType, unsigned numElements) static
Definition at line 734 of file FIRRTLTypes.cpp.
References circt::firrtl::FlipType::get().
Referenced by circt::firrtl::FlipType::get(), circt::firrtl::FIRRTLType::getMaskType(), getPassiveType(), circt::firrtl::FIRRTLType::getWidthlessType(), and parseType().
getElementType()
FIRRTLType FVectorType::getElementType ()
Definition at line 743 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::areTypesEquivalent(), circt::firrtl::FlipType::get(), and circt::firrtl::FIRRTLType::getMaskType().
getNumElements()
unsigned FVectorType::getNumElements ()
Definition at line 745 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::areTypesEquivalent(), circt::firrtl::FlipType::get(), and circt::firrtl::FIRRTLType::getMaskType().
getPassiveType()
FIRRTLType FVectorType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 755 of file FIRRTLTypes.cpp.
References get(), circt::firrtl::FIRRTLType::getPassiveType(), and IsPassiveBitMask.
Referenced by circt::firrtl::FIRRTLType::getPassiveType().
getRecursiveTypeProperties()
std::pair< bool, bool > FVectorType::getRecursiveTypeProperties ()
Return a pair with the 'isPassive' and 'containsAnalog' bits.
Definition at line 748 of file FIRRTLTypes.cpp.
References ContainsAnalogBitMask, and IsPassiveBitMask.
Referenced by circt::firrtl::FlipType::get(), and circt::firrtl::FIRRTLType::getRecursiveTypeProperties().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp