CIRCT: circt::llhd::ArrayType Class Reference
circt::llhd::ArrayType Class Reference
#include <LLHDDialect.h>
Public Member Functions
unsigned getLength () const
Type getElementType () const
Static Public Member Functions
static ArrayType get (unsigned length, Type elementType)
Get or create a new ArrayType of the provided length and element type.
static ArrayType getChecked (unsigned length, Type elementType, Location location)
Get or create a new ArrayType of the provided length and element type declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, unsigned length, Type elementType)
Verify the construction of an array type.
static llvm::StringRef getKeyword ()
Get the keyword for the array type.
Detailed Description
Definition at line 107 of file LLHDDialect.h.
Member Function Documentation
get()
ArrayType ArrayType::get (unsigned length, Type elementType) static
Get or create a new ArrayType of the provided length and element type.
Assumes the arguments define a well-formed ArrayType.
Definition at line 415 of file LLHDDialect.cpp.
Referenced by convertTupleType(), and parseArrayType().
getChecked()
ArrayType ArrayType::getChecked (unsigned length, Type elementType, Location location) static
Get or create a new ArrayType of the provided length and element type declared at the given, potentially unknown, location.
If the ArrayType defined by the arguments would be ill-formed, emit errors and return nullptr-wrapping type.
Definition at line 419 of file LLHDDialect.cpp.
getElementType()
Type ArrayType::getElementType () const
Definition at line 434 of file LLHDDialect.cpp.
Referenced by convertArrayType().
getKeyword()
static llvm::StringRef circt::llhd::ArrayType::getKeyword () inline static
Get the keyword for the array type.
Definition at line 131 of file LLHDDialect.h.
Referenced by circt::llhd::LLHDDialect::parseType().
getLength()
unsigned ArrayType::getLength () const
Definition at line 433 of file LLHDDialect.cpp.
Referenced by convertArrayType().
verifyConstructionInvariants()
LogicalResult ArrayType::verifyConstructionInvariants (Location loc, unsigned length, Type elementType) static
Verify the construction of an array type.
Definition at line 424 of file LLHDDialect.cpp.
The documentation for this class was generated from the following files:
include/circt/Dialect/LLHD/IR/LLHDDialect.h
lib/Dialect/LLHD/IR/LLHDDialect.cpp
lib/Dialect/RTL/RTLTypes.cpp