CIRCT: circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs > Class Template Reference
circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs > Class Template Reference
This helps visit Combinatorial nodes.
#include <RTLVisitors.h>
Public Member Functions
ResultType dispatchCombinatorialVisitor (Operation *op, ExtraArgs... args)
ResultType visitInvalidComb (Operation *op, ExtraArgs... args)
This callback is invoked on any non-expression operations.
ResultType visitUnhandledComb (Operation *op, ExtraArgs... args)
This callback is invoked on any combinatorial operations that are not handled by the concrete visitor.
ResultType visitBinaryComb (Operation *op, ExtraArgs... args)
This fallback is invoked on any binary node that isn't explicitly handled.
ResultType visitUnaryComb (Operation *op, ExtraArgs... args)
ResultType visitVariadicComb (Operation *op, ExtraArgs... args)
HANDLE (ConstantOp, Unhandled)
HANDLE (AddOp, Binary)
HANDLE (SubOp, Binary)
HANDLE (MulOp, Binary)
HANDLE (DivUOp, Binary)
HANDLE (DivSOp, Binary)
HANDLE (ModUOp, Binary)
HANDLE (ModSOp, Binary)
HANDLE (ShlOp, Binary)
HANDLE (ShrUOp, Binary)
HANDLE (ShrSOp, Binary)
HANDLE (AndOp, Variadic)
HANDLE (OrOp, Variadic)
HANDLE (XorOp, Variadic)
HANDLE (AndROp, Unary)
HANDLE (OrROp, Unary)
HANDLE (XorROp, Unary)
HANDLE (ICmpOp, Binary)
HANDLE (SExtOp, Unhandled)
HANDLE (ConcatOp, Unhandled)
HANDLE (ExtractOp, Unhandled)
HANDLE (MuxOp, Unhandled)
HANDLE (BitcastOp, Unary)
HANDLE (ArraySliceOp, Unhandled)
HANDLE (ArrayGetOp, Unhandled)
HANDLE (ArrayCreateOp, Unhandled)
Detailed Description
template<typename ConcreteType, typename ResultType = void, typename... ExtraArgs>
class circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >
This helps visit Combinatorial nodes.
Definition at line 25 of file RTLVisitors.h.
Member Function Documentation
dispatchCombinatorialVisitor()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchCombinatorialVisitor (Operation * op, ExtraArgs... args) inline
Definition at line 27 of file RTLVisitors.h.
Referenced by circt::rtl::isCombinatorial().
HANDLE() [1/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ConstantOp , Unhandled)
Referenced by circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitVariadicComb().
HANDLE() [2/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AddOp , Binary)
HANDLE() [3/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubOp , Binary)
HANDLE() [4/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (MulOp , Binary)
HANDLE() [5/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DivUOp , Binary)
HANDLE() [6/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DivSOp , Binary)
HANDLE() [7/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ModUOp , Binary)
HANDLE() [8/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ModSOp , Binary)
HANDLE() [9/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ShlOp , Binary)
HANDLE() [10/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ShrUOp , Binary)
HANDLE() [11/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ShrSOp , Binary)
HANDLE() [12/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AndOp , Variadic)
HANDLE() [13/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OrOp , Variadic)
HANDLE() [14/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XorOp , Variadic)
HANDLE() [15/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AndROp , Unary)
HANDLE() [16/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OrROp , Unary)
HANDLE() [17/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XorROp , Unary)
HANDLE() [18/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ICmpOp , Binary)
HANDLE() [19/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SExtOp , Unhandled)
HANDLE() [20/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ConcatOp , Unhandled)
HANDLE() [21/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ExtractOp , Unhandled)
HANDLE() [22/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (MuxOp , Unhandled)
HANDLE() [23/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (BitcastOp , Unary)
HANDLE() [24/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ArraySliceOp , Unhandled)
HANDLE() [25/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ArrayGetOp , Unhandled)
HANDLE() [26/26]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ArrayCreateOp , Unhandled)
visitBinaryComb()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitBinaryComb (Operation * op, ExtraArgs... args) inline
This fallback is invoked on any binary node that isn't explicitly handled.
The default implementation delegates to the 'unhandled' fallback.
Definition at line 68 of file RTLVisitors.h.
References circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledComb().
visitInvalidComb()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitInvalidComb (Operation * op, ExtraArgs... args) inline
This callback is invoked on any non-expression operations.
Definition at line 55 of file RTLVisitors.h.
visitUnaryComb()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnaryComb (Operation * op, ExtraArgs... args) inline
Definition at line 72 of file RTLVisitors.h.
References circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledComb().
visitUnhandledComb()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledComb (Operation * op, ExtraArgs... args) inline
This callback is invoked on any combinatorial operations that are not handled by the concrete visitor.
Definition at line 62 of file RTLVisitors.h.
Referenced by circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitBinaryComb(), circt::rtl::StmtVisitor< ConcreteType, ResultType, ExtraArgs >::visitBinaryComb(), circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnaryComb(), circt::rtl::StmtVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnaryComb(), and circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitVariadicComb().
visitVariadicComb()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitVariadicComb (Operation * op, ExtraArgs... args) inline
Definition at line 76 of file RTLVisitors.h.
References circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE(), and circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledComb().
The documentation for this class was generated from the following file:
include/circt/Dialect/RTL/RTLVisitors.h