CIRCT: circt::llhd::LLHDDialect Class Reference
circt::llhd::LLHDDialect Class Reference
#include <LLHDDialect.h>
Public Member Functions
LLHDDialect (MLIRContext *context)
Type parseType (DialectAsmParser &parser) const override
Parses a type registered to this dialect.
void printType (Type type, DialectAsmPrinter &printer) const override
Print a type registered to this dialect.
Attribute parseAttribute (DialectAsmParser &parser, Type type) const override
Parse an attribute regustered to this dialect.
void printAttribute (Attribute attr, DialectAsmPrinter &printer) const override
Print an attribute registered to this dialect.
Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc) override
Static Public Member Functions
static StringRef getDialectNamespace ()
Returns the prefix used in the textual IR to refer to LLHD operations.
Detailed Description
Definition at line 30 of file LLHDDialect.h.
Constructor & Destructor Documentation
LLHDDialect()
LLHDDialect::LLHDDialect (MLIRContext * context) explicit
Definition at line 57 of file LLHDDialect.cpp.
Member Function Documentation
getDialectNamespace()
static StringRef circt::llhd::LLHDDialect::getDialectNamespace () inline static
Returns the prefix used in the textual IR to refer to LLHD operations.
Definition at line 35 of file LLHDDialect.h.
References parseType().
materializeConstant()
Operation * LLHDDialect::materializeConstant (OpBuilder & builder, Attribute value, Type type, Location loc) override
Definition at line 69 of file LLHDDialect.cpp.
parseAttribute()
Attribute LLHDDialect::parseAttribute (DialectAsmParser & parser, Type type) const override
Parse an attribute regustered to this dialect.
Parse an LLHD attribute.
Definition at line 213 of file LLHDDialect.cpp.
References circt::llhd::TimeAttr::getKeyword(), and parseTimeAttribute().
parseType()
Type LLHDDialect::parseType (DialectAsmParser & parser) const override
Parses a type registered to this dialect.
Definition at line 129 of file LLHDDialect.cpp.
References circt::llhd::TimeType::get(), circt::llhd::SigType::getKeyword(), circt::llhd::TimeType::getKeyword(), circt::llhd::PtrType::getKeyword(), circt::llhd::ArrayType::getKeyword(), parseArrayType(), parsePtrType(), and parseSigType().
printAttribute()
void LLHDDialect::printAttribute (Attribute attr, DialectAsmPrinter & printer) const override
Print an attribute registered to this dialect.
Definition at line 240 of file LLHDDialect.cpp.
References printTimeAttribute().
printType()
void LLHDDialect::printType (Type type, DialectAsmPrinter & printer) const override
Print a type registered to this dialect.
Definition at line 159 of file LLHDDialect.cpp.
References printSigType().
The documentation for this class was generated from the following files:
include/circt/Dialect/LLHD/IR/LLHDDialect.h
lib/Dialect/LLHD/IR/LLHDDialect.cpp