CIRCT: circt::esi::ESIDialect Class Reference
circt::esi::ESIDialect Class Reference
#include <ESIDialect.h>
Public Member Functions
ESIDialect (mlir::MLIRContext *context)
mlir::Type parseType (mlir::DialectAsmParser &parser) const override
Parses a type registered to this dialect.
void printType (mlir::Type type, mlir::DialectAsmPrinter &printer) const override
Print a type registered to this dialect.
Static Public Member Functions
static llvm::StringRef getDialectNamespace ()
Returns the prefix used in the textual IR to refer to ESI operations.
Detailed Description
Definition at line 27 of file ESIDialect.h.
Constructor & Destructor Documentation
ESIDialect()
circt::esi::ESIDialect::ESIDialect (mlir::MLIRContext * context) explicit
Definition at line 26 of file ESIDialect.cpp.
Member Function Documentation
getDialectNamespace()
static llvm::StringRef circt::esi::ESIDialect::getDialectNamespace () inline static
Returns the prefix used in the textual IR to refer to ESI operations.
Definition at line 32 of file ESIDialect.h.
References parseType(), printType(), circt::esi::registerESIPasses(), and circt::esi::registerESITranslations().
parseType()
Type ESIDialect::parseType (mlir::DialectAsmParser & parser) const override
Parses a type registered to this dialect.
Definition at line 40 of file ESITypes.cpp.
Referenced by getDialectNamespace().
printType()
void ESIDialect::printType (mlir::Type type, mlir::DialectAsmPrinter & printer) const override
Print a type registered to this dialect.
Definition at line 53 of file ESITypes.cpp.
Referenced by getDialectNamespace().
The documentation for this class was generated from the following files:
include/circt/Dialect/ESI/ESIDialect.h
lib/Dialect/ESI/ESIDialect.cpp
lib/Dialect/ESI/ESITypes.cpp