CIRCT: lib/Dialect/ESI/ESIOps.cpp File Reference
ESIOps.cpp File Reference
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/RTL/RTLTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/SV/SVTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/SymbolTable.h"
#include "circt/Dialect/ESI/ESI.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static ParseResult parseChannelBuffer (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ChannelBuffer &op)
static ParseResult parsePipelineStage (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, PipelineStage &op)
static ParseResult parseWrapValidReady (OpAsmParser &parser, OperationState &result)
void print (OpAsmPrinter &p, WrapValidReady &op)
static ParseResult parseUnwrapValidReady (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, UnwrapValidReady &op)
static Type getEsiDataType (circt::sv::InterfaceOp iface)
If 'iface' looks like an ESI interface, return the inner data type.
static LogicalResult verifySVInterface (Operation *op, circt::sv::ModportType modportType, ChannelPort chanType)
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
static LogicalResult verifyWrapSVInterface (WrapSVInterface &op)
static LogicalResult verifyUnwrapSVInterface (UnwrapSVInterface &op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 221 of file ESIOps.cpp.
Function Documentation
getEsiDataType()
static Type getEsiDataType (circt::sv::InterfaceOp iface) static
If 'iface' looks like an ESI interface, return the inner data type.
Definition at line 172 of file ESIOps.cpp.
Referenced by verifySVInterface().
parseChannelBuffer()
static ParseResult parseChannelBuffer (OpAsmParser & parser, OperationState & result) static
Definition at line 29 of file ESIOps.cpp.
parsePipelineStage()
static ParseResult parsePipelineStage (OpAsmParser & parser, OperationState & result) static
Definition at line 71 of file ESIOps.cpp.
parseUnwrapValidReady()
static ParseResult parseUnwrapValidReady (OpAsmParser & parser, OperationState & result) static
Definition at line 136 of file ESIOps.cpp.
parseWrapValidReady()
static ParseResult parseWrapValidReady (OpAsmParser & parser, OperationState & result) static
Definition at line 103 of file ESIOps.cpp.
print() [1/4]
static void print (OpAsmPrinter & p, ChannelBuffer & op) static
Definition at line 59 of file ESIOps.cpp.
print() [2/4]
static void print (OpAsmPrinter & p, PipelineStage & op) static
Definition at line 92 of file ESIOps.cpp.
print() [3/4]
void print (OpAsmPrinter & p, WrapValidReady & op)
Definition at line 124 of file ESIOps.cpp.
Referenced by circt::sv::getInOutElementType(), circt::rtl::hash_value(), and circt::firrtl::FIRRTLDialect::printType().
print() [4/4]
static void print (OpAsmPrinter & p, UnwrapValidReady & op) static
Definition at line 159 of file ESIOps.cpp.
verifySVInterface()
static LogicalResult verifySVInterface (Operation * op, circt::sv::ModportType modportType, ChannelPort chanType) static
Verify that the modport type of 'modportArg' points to an interface which looks like an ESI interface and the inner data from said interface matches the chan type's inner data type.
Definition at line 187 of file ESIOps.cpp.
References getEsiDataType().
Referenced by verifyUnwrapSVInterface(), and verifyWrapSVInterface().
verifyUnwrapSVInterface()
static LogicalResult verifyUnwrapSVInterface (UnwrapSVInterface & op) static
Definition at line 214 of file ESIOps.cpp.
References verifySVInterface().
verifyWrapSVInterface()
static LogicalResult verifyWrapSVInterface (WrapSVInterface & op) static
Definition at line 207 of file ESIOps.cpp.
References verifySVInterface().