CIRCT: lib/Translation/ExportVerilog/ExportVerilogFIRRTL.cpp File Reference
ExportVerilogFIRRTL.cpp File Reference
#include "circt/Translation/ExportVerilog.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Translation.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "ReservedWords.def"
Enumerations
enum VerilogPrecedence
This enum keeps track of the precedence level of various binary operators, where a lower number binds tighter.
enum SubExprSignedness
This enum keeps track of whether the emitted subexpression is signed or unsigned as seen from the Verilog language perspective.
Functions
static bool isVerilogExpression (Operation *op)
static int getBitWidthOrSentinel (Type type)
Return the width of the specified FIRRTL type in bits or -1 if it isn't supported.
template<typename T = FIRRTLType>
static T getTypeOf (Value v)
Return the type of the specified value, force casting to the subtype.
static unsigned getPrintedIntWidth (unsigned value)
Given an integer value, return the number of characters it will take to print its base-10 value.
static bool isNoopCast (Operation *op)
Return true if this is a noop cast that will emit with no syntax.
static void flattenBundleTypes (Type type, StringRef suffixSoFar, bool isFlipped, SmallVectorImpl< FlatBundleFieldEntry > &results)
Convert a nested bundle of fields into a flat list of fields.
static const StringSet & getReservedWords ()
Return a StringSet that contains all of the reserved names (e.g.
static SubExprSignedness getSignednessOf (Type type)
Return the verilog signedness of the specified type.
static void collectCatValues (Value operand, SmallVectorImpl< Value > &catValues, ExprEmitter &emitter)
static bool isOkToBitSelectFrom (Value v)
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
static bool isExpressionUnableToInline (Operation *op)
Return true if we are unable to ever inline the specified operation.
static bool isExpressionAlwaysInline (Operation *op)
Return true for operations that are always inlined.
static bool isExpressionEmittedInline (Operation *op)
Return true if this expression should be emitted inline into any statement that uses it.
template<typename Compare >
static void splitByPredicate (ModuleEmitter &emitter, ArrayRef< ModuleEmitter::ConditionalStatement > fullList, std::function< void(ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)> visitFn, const Compare &elementFn)
Split the ArrayRef (which is known to be sorted) into chunks where the specified elementFn matches.
static void emitActionByCond (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)
Emit a group of actions, with a fixed condition.
static void emitCondActionByPPCond (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)
Emit a group of actions, guarded by conditions, with a fixed mode.
static void emitPosEdgeByClock (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)
Emit a group of "always @(posedge)" conditional statements with a matching clock declaration.
static void emitConditionStmtKind (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)
Emit a block of conditional statements that have the same ConditionStmtKind.
Variables
static constexpr bool emitInlineWireDecls = true
Should we emit wire decls in a block at the top of a module, or inline?
static constexpr size_t preferredSourceWidth = 120
This is the preferred source width for the generated Verilog.
static llvm::ManagedStatic< StringSet<> > reservedWordCache
This is a set accessed through getReservedWords() that contains all of the Verilog names and other identifiers we need to avoid because of name conflicts.
Enumeration Type Documentation
SubExprSignedness
enum SubExprSignedness
This enum keeps track of whether the emitted subexpression is signed or unsigned as seen from the Verilog language perspective.
Definition at line 636 of file ExportVerilogFIRRTL.cpp.
VerilogPrecedence
enum VerilogPrecedence
This enum keeps track of the precedence level of various binary operators, where a lower number binds tighter.
Definition at line 165 of file ExportVerilogFIRRTL.cpp.
Function Documentation
collectCatValues()
static void collectCatValues (Value operand, SmallVectorImpl< Value > & catValues, ExprEmitter & emitter) static
Definition at line 1030 of file ExportVerilogFIRRTL.cpp.
References emitInlineWireDecls, flattenBundleTypes(), getBitWidthOrSentinel(), and circt::firrtl::IntType::getWidth().
emitActionByCond()
static void emitActionByCond (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter & emitter) static
Emit a group of actions, with a fixed condition.
Definition at line 1994 of file ExportVerilogFIRRTL.cpp.
Referenced by emitCondActionByPPCond().
emitCondActionByPPCond()
static void emitCondActionByPPCond (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter & emitter) static
Emit a group of actions, guarded by conditions, with a fixed mode.
Definition at line 2041 of file ExportVerilogFIRRTL.cpp.
References emitActionByCond(), and splitByPredicate().
Referenced by emitConditionStmtKind(), and emitPosEdgeByClock().
emitConditionStmtKind()
static void emitConditionStmtKind (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter & emitter) static
Emit a block of conditional statements that have the same ConditionStmtKind.
Definition at line 2086 of file ExportVerilogFIRRTL.cpp.
References emitCondActionByPPCond(), emitPosEdgeByClock(), circt::exportFIRRTLToVerilog(), getBitWidthOrSentinel(), getPrintedIntWidth(), preferredSourceWidth, and splitByPredicate().
emitPosEdgeByClock()
static void emitPosEdgeByClock (ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter & emitter) static
Emit a group of "always @(posedge)" conditional statements with a matching clock declaration.
Definition at line 2072 of file ExportVerilogFIRRTL.cpp.
References emitCondActionByPPCond(), and splitByPredicate().
Referenced by emitConditionStmtKind().
flattenBundleTypes()
static void flattenBundleTypes (Type type, StringRef suffixSoFar, bool isFlipped, SmallVectorImpl< FlatBundleFieldEntry > & results) static
Convert a nested bundle of fields into a flat list of fields.
This is used when working with instances and mems to flatten them.
Definition at line 136 of file ExportVerilogFIRRTL.cpp.
Referenced by collectCatValues(), and isExpressionEmittedInline().
getBitWidthOrSentinel()
static int getBitWidthOrSentinel (Type type) static
Return the width of the specified FIRRTL type in bits or -1 if it isn't supported.
Definition at line 52 of file ExportVerilogFIRRTL.cpp.
References circt::firrtl::FlipType::getElementType(), circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::getWidthOrSentinel(), and circt::firrtl::IntType::getWidthOrSentinel().
Referenced by collectCatValues(), emitConditionStmtKind(), getReservedWords(), and isExpressionEmittedInline().
getPrintedIntWidth()
static unsigned getPrintedIntWidth (unsigned value) static
Given an integer value, return the number of characters it will take to print its base-10 value.
Definition at line 87 of file ExportVerilogFIRRTL.cpp.
Referenced by emitConditionStmtKind(), getReservedWords(), and isExpressionEmittedInline().
getReservedWords()
static const StringSet& getReservedWords () static
Return a StringSet that contains all of the reserved names (e.g.
Verilog keywords) that we need to avoid for fear of name conflicts.
Definition at line 187 of file ExportVerilogFIRRTL.cpp.
References getBitWidthOrSentinel(), getPrintedIntWidth(), isalpha, isdigit, and reservedWordCache.
getSignednessOf()
static SubExprSignedness getSignednessOf (Type type) static
Return the verilog signedness of the specified type.
Definition at line 653 of file ExportVerilogFIRRTL.cpp.
References circt::firrtl::FlipType::getElementType(), isNoopCast(), and isVerilogExpression().
getTypeOf()
template<typename T = FIRRTLType> static T getTypeOf (Value v) static
Return the type of the specified value, force casting to the subtype.
Definition at line 81 of file ExportVerilogFIRRTL.cpp.
isExpressionAlwaysInline()
static bool isExpressionAlwaysInline (Operation * op) static
Return true for operations that are always inlined.
Definition at line 1731 of file ExportVerilogFIRRTL.cpp.
References isNoopCast().
Referenced by isExpressionEmittedInline().
isExpressionEmittedInline()
static bool isExpressionEmittedInline (Operation * op) static
Return true if this expression should be emitted inline into any statement that uses it.
Definition at line 1746 of file ExportVerilogFIRRTL.cpp.
References emitInlineWireDecls, flattenBundleTypes(), getBitWidthOrSentinel(), getPrintedIntWidth(), isExpressionAlwaysInline(), isExpressionUnableToInline(), isVerilogExpression(), and size().
isExpressionUnableToInline()
static bool isExpressionUnableToInline (Operation * op) static
Return true if we are unable to ever inline the specified operation.
This happens because not all Verilog expressions are composable, notably you can only use bit selects like x[4:6] on simple expressions.
Definition at line 1706 of file ExportVerilogFIRRTL.cpp.
References isOkToBitSelectFrom().
Referenced by isExpressionEmittedInline().
isNoopCast()
static bool isNoopCast (Operation * op) static
Return true if this is a noop cast that will emit with no syntax.
Definition at line 102 of file ExportVerilogFIRRTL.cpp.
Referenced by getSignednessOf(), and isExpressionAlwaysInline().
isOkToBitSelectFrom()
static bool isOkToBitSelectFrom (Value v) static
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
Return true if it is ok to inline bitselect from the result of this expression. It is conservatively correct to return false.
Definition at line 1684 of file ExportVerilogFIRRTL.cpp.
Referenced by isExpressionUnableToInline().
isVerilogExpression()
static bool isVerilogExpression (Operation * op) static
Definition at line 43 of file ExportVerilogFIRRTL.cpp.
References circt::firrtl::isExpression().
Referenced by getSignednessOf(), and isExpressionEmittedInline().
splitByPredicate()
template<typename Compare > static void splitByPredicate (ModuleEmitter & emitter, ArrayRef< ModuleEmitter::ConditionalStatement > fullList, std::function< void(ArrayRef< ModuleEmitter::ConditionalStatement > elements, ModuleEmitter &emitter)> visitFn, const Compare & elementFn) static
Split the ArrayRef (which is known to be sorted) into chunks where the specified elementFn matches.
The visitFn is invoked for every element.
Definition at line 1969 of file ExportVerilogFIRRTL.cpp.
Referenced by emitCondActionByPPCond(), emitConditionStmtKind(), and emitPosEdgeByClock().
Variable Documentation
emitInlineWireDecls
constexpr bool emitInlineWireDecls = true static
Should we emit wire decls in a block at the top of a module, or inline?
Definition at line 29 of file ExportVerilogFIRRTL.cpp.
Referenced by collectCatValues(), and isExpressionEmittedInline().
preferredSourceWidth
constexpr size_t preferredSourceWidth = 120 static
This is the preferred source width for the generated Verilog.
Definition at line 32 of file ExportVerilogFIRRTL.cpp.
Referenced by emitConditionStmtKind().
reservedWordCache
llvm::ManagedStatic<StringSet<> > reservedWordCache static
This is a set accessed through getReservedWords() that contains all of the Verilog names and other identifiers we need to avoid because of name conflicts.
Definition at line 37 of file ExportVerilogFIRRTL.cpp.
Referenced by getReservedWords().