CIRCT: lib/Dialect/FIRRTL/Import/FIRParser.cpp File Reference
FIRParser.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRParser.h"
#include "FIRLexer.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Translation.h"
#include "llvm/ADT/PointerEmbeddedInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include "FIRTokenKinds.def"
Classes
class FIRParser::LocWithInfo
This helper class is used to handle Info records, which specify higher level symbolic source location, that may be missing from the file.
Macros
#define TOK_KEYWORD(spelling) case FIRToken::kw_##spelling:
#define TOK_LPKEYWORD(SPELLING) case FIRToken::lp_##SPELLING:
#define TOK_LPKEYWORD_PRIM(SPELLING, CLASS)
Functions
static bool isUselessName (StringRef name)
Return true if this is a useless temporary name produced by FIRRTL.
static StringAttr filterUselessName (StringAttr name)
If the specified name is a useless temporary name produced by FIRRTL, return an empty attribute to ignore it.
Macro Definition Documentation
TOK_KEYWORD
#define TOK_KEYWORD (spelling) case FIRToken::kw_##spelling:
TOK_LPKEYWORD
#define TOK_LPKEYWORD (SPELLING) case FIRToken::lp_##SPELLING:
TOK_LPKEYWORD_PRIM
#define TOK_LPKEYWORD_PRIM (SPELLING, CLASS)
Value:
case FIRToken::lp_##SPELLING: {                                              \
    auto resultTy =                                                            \
        CLASS::getResultType(opTypes, integers, translateLocation(loc));       \
    if (!resultTy)                                                             \
      return failure();                                                        \
    result = builder.create<CLASS>(translateLocation(loc), resultTy,           \
                                   ValueRange(operands), attrs);               \
    break;                                                                     \
  }
Function Documentation
filterUselessName()
static StringAttr filterUselessName (StringAttr name) static
If the specified name is a useless temporary name produced by FIRRTL, return an empty attribute to ignore it.
Otherwise, return the argument unmodified.
Definition at line 57 of file FIRParser.cpp.
References isUselessName(), and parseType().
isUselessName()
static bool isUselessName (StringRef name) static
Return true if this is a useless temporary name produced by FIRRTL.
We drop these as they don't convey semantic meaning.
Definition at line 38 of file FIRParser.cpp.
Referenced by filterUselessName().