CIRCT: lib/Dialect/FIRRTL/FIRRTLFolds.cpp File Reference
FIRRTLFolds.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
Functions
static Attribute getIntAttr (const APInt &value, MLIRContext *context)
static ConstantIntMatcher m_FConstant (APInt &value)
static void replaceWithBits (Operation *op, Value value, unsigned hiBit, unsigned loBit, PatternRewriter &rewriter)
Replace the specified operation with a 'bits' op from the specified hi/lo bits.
Function Documentation
getIntAttr()
static Attribute getIntAttr (const APInt & value, MLIRContext * context) static
Definition at line 21 of file FIRRTLFolds.cpp.
Referenced by m_FConstant(), and replaceWithBits().
m_FConstant()
static ConstantIntMatcher m_FConstant (APInt & value) inline static
Definition at line 40 of file FIRRTLFolds.cpp.
References getIntAttr(), and circt::firrtl::IntType::hasWidth().
Referenced by replaceWithBits().
replaceWithBits()
static void replaceWithBits (Operation * op, Value value, unsigned hiBit, unsigned loBit, PatternRewriter & rewriter) static
Replace the specified operation with a 'bits' op from the specified hi/lo bits.
Insert a cast to handle the case where the original operation returned a signed integer.
Definition at line 288 of file FIRRTLFolds.cpp.
References getIntAttr(), circt::firrtl::IntType::getWidth(), circt::firrtl::IntType::getWidthOrSentinel(), and m_FConstant().