CIRCT: lib/Dialect/FIRRTL/FIRRTLOps.cpp File Reference
FIRRTLOps.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/RTL/RTLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "llvm/ADT/DenseMap.h"
#include "circt/Dialect/FIRRTL/FIRRTL.cpp.inc"
Macros
#define VERIFY_RESULT_TYPE(...)
#define VERIFY_RESULT_TYPE_RET(...)
#define GET_OP_CLASSES
Functions
static void print (OpAsmPrinter &p, CircuitOp op)
static ParseResult parseCircuitOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyCircuitOp (CircuitOp circuit)
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< ModulePortInfo > ports)
static void printFunctionSignature2 (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
static void printModuleLikeOp (OpAsmPrinter &p, Operation *op)
static void print (OpAsmPrinter &p, FExtModuleOp op)
static void print (OpAsmPrinter &p, FModuleOp op)
static ParseResult parseFModuleOp (OpAsmParser &parser, OperationState &result, bool isExtModule=false)
static ParseResult parseFExtModuleOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyModuleSignature (Operation *op)
static LogicalResult verifyFModuleOp (FModuleOp op)
static LogicalResult verifyFExtModuleOp (FExtModuleOp op)
static LogicalResult verifyInstanceOp (InstanceOp instance)
Verify the correctness of an InstanceOp.
static Optional< MemOp::PortKind > getMemPortKindFromType (FIRRTLType type)
Return the kind of port this is given the port type from a 'mem' decl.
static LogicalResult verifyConnectOp (ConnectOp connect)
static LogicalResult verifyConstantOp (ConstantOp constant)
static bool isSameIntTypeKind (FIRRTLType lhs, FIRRTLType rhs, int32_t &lhsWidth, int32_t &rhsWidth, Location loc)
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
static FIRRTLType getAddSubResult (FIRRTLType lhs, FIRRTLType rhs, Location loc)
static FIRRTLType getBitwiseBinaryResult (FIRRTLType lhs, FIRRTLType rhs, Location loc)
static FIRRTLType getCompareResult (FIRRTLType lhs, FIRRTLType rhs, Location loc)
static FIRRTLType getReductionResult (FIRRTLType input, Location loc)
static LogicalResult verifyStdIntCastOp (StdIntCastOp cast)
static LogicalResult verifyAnalogInOutCastOp (AnalogInOutCastOp cast)
static LogicalResult verifyRTLStructCastOp (RTLStructCastOp cast)
static ParseResult parseImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1572 of file FIRRTLOps.cpp.
VERIFY_RESULT_TYPE
#define VERIFY_RESULT_TYPE (...)
Value:
{                                                                            \
    auto resType = getResultType(__VA_ARGS__, getLoc());                       \
    if (!resType)                                                              \
      return failure(); /*already diagnosed the error*/                        \
    if (resType != getType())                                                  \
      return emitOpError("result type should be ") << resType;                 \
  }
Definition at line 34 of file FIRRTLOps.cpp.
VERIFY_RESULT_TYPE_RET
#define VERIFY_RESULT_TYPE_RET (...)
Value:
VERIFY_RESULT_TYPE(__VA_ARGS__);                                             \
  return success();
Definition at line 45 of file FIRRTLOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< ModulePortInfo > ports) static
Definition at line 245 of file FIRRTLOps.cpp.
getAddSubResult()
static FIRRTLType getAddSubResult (FIRRTLType lhs, FIRRTLType rhs, Location loc) static
Definition at line 948 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::get(), circt::firrtl::SIntType::get(), circt::firrtl::UIntType::get(), and isSameIntTypeKind().
getBitwiseBinaryResult()
static FIRRTLType getBitwiseBinaryResult (FIRRTLType lhs, FIRRTLType rhs, Location loc) static
Definition at line 1007 of file FIRRTLOps.cpp.
References circt::firrtl::UIntType::get(), and isSameIntTypeKind().
getCompareResult()
static FIRRTLType getCompareResult (FIRRTLType lhs, FIRRTLType rhs, Location loc) static
Definition at line 1031 of file FIRRTLOps.cpp.
References circt::firrtl::ClockType::get(), circt::firrtl::AsyncResetType::get(), circt::firrtl::IntType::get(), circt::firrtl::SIntType::get(), circt::firrtl::UIntType::get(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), circt::firrtl::IntType::getWidth(), and isSameIntTypeKind().
getMemPortKindFromType()
static Optional<MemOp::PortKind> getMemPortKindFromType (FIRRTLType type) static
Return the kind of port this is given the port type from a 'mem' decl.
Definition at line 677 of file FIRRTLOps.cpp.
References circt::firrtl::BundleType::getElementType(), and circt::firrtl::FIRRTLType::getPassiveType().
getReductionResult()
static FIRRTLType getReductionResult (FIRRTLType input, Location loc) static
Definition at line 1210 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::get(), circt::firrtl::UIntType::get(), and circt::firrtl::FIRRTLType::getBitWidthOrSentinel().
isSameIntTypeKind()
static bool isSameIntTypeKind (FIRRTLType lhs, FIRRTLType rhs, int32_t & lhsWidth, int32_t & rhsWidth, Location loc) static
If LHS and RHS are both UInt or SInt types, the return true and fill in the width of them if known.
If unknown, return -1 for the widths.
On failure, this reports and error and returns false. This function should not be used if you don't want an error reported.
Definition at line 923 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::isSigned().
Referenced by getAddSubResult(), getBitwiseBinaryResult(), and getCompareResult().
parseCircuitOp()
static ParseResult parseCircuitOp (OpAsmParser & parser, OperationState & result) static
Definition at line 77 of file FIRRTLOps.cpp.
parseFExtModuleOp()
static ParseResult parseFExtModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 477 of file FIRRTLOps.cpp.
References parseFModuleOp().
parseFModuleOp()
static ParseResult parseFModuleOp (OpAsmParser & parser, OperationState & result, bool isExtModule = false) static
Definition at line 391 of file FIRRTLOps.cpp.
References isdigit.
Referenced by parseFExtModuleOp().
parseImplicitSSAName()
static ParseResult parseImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 1518 of file FIRRTLOps.cpp.
References isdigit.
print() [1/3]
static void print (OpAsmPrinter & p, CircuitOp op) static
Definition at line 66 of file FIRRTLOps.cpp.
print() [2/3]
static void print (OpAsmPrinter & p, FExtModuleOp op) static
Definition at line 377 of file FIRRTLOps.cpp.
References printModuleLikeOp().
print() [3/3]
static void print (OpAsmPrinter & p, FModuleOp op) static
Definition at line 381 of file FIRRTLOps.cpp.
References printModuleLikeOp().
printFunctionSignature2()
static void printFunctionSignature2 (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes) static
Definition at line 302 of file FIRRTLOps.cpp.
References getArgAttrs(), and circt::firrtl::getFIRRTLNameAttr().
Referenced by printModuleLikeOp().
printImplicitSSAName()
static void printImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 1545 of file FIRRTLOps.cpp.
printModuleLikeOp()
static void printModuleLikeOp (OpAsmPrinter & p, Operation * op) static
Definition at line 356 of file FIRRTLOps.cpp.
References circt::firrtl::getModuleType(), and printFunctionSignature2().
Referenced by print().
verifyAnalogInOutCastOp()
static LogicalResult verifyAnalogInOutCastOp (AnalogInOutCastOp cast) static
Definition at line 1433 of file FIRRTLOps.cpp.
verifyCircuitOp()
static LogicalResult verifyCircuitOp (CircuitOp circuit) static
Definition at line 96 of file FIRRTLOps.cpp.
References circt::firrtl::FIRRTLType::getWidthlessType().
verifyConnectOp()
static LogicalResult verifyConnectOp (ConnectOp connect) static
Definition at line 752 of file FIRRTLOps.cpp.
References circt::firrtl::areTypesEquivalent(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), and circt::firrtl::getPassiveType().
verifyConstantOp()
static LogicalResult verifyConstantOp (ConstantOp constant) static
Definition at line 828 of file FIRRTLOps.cpp.
References circt::firrtl::FlipType::get(), circt::firrtl::IntType::getWidthOrSentinel(), and circt::firrtl::IntType::isSigned().
verifyFExtModuleOp()
static LogicalResult verifyFExtModuleOp (FExtModuleOp op) static
Definition at line 499 of file FIRRTLOps.cpp.
References verifyModuleSignature().
verifyFModuleOp()
static LogicalResult verifyFModuleOp (FModuleOp op) static
Definition at line 489 of file FIRRTLOps.cpp.
References verifyModuleSignature().
verifyInstanceOp()
static LogicalResult verifyInstanceOp (InstanceOp instance) static
Verify the correctness of an InstanceOp.
Definition at line 566 of file FIRRTLOps.cpp.
References circt::firrtl::ClockType::get(), circt::firrtl::UIntType::get(), circt::firrtl::FlipType::get(), circt::firrtl::BundleType::get(), circt::firrtl::FIRRTLType::getMaskType(), and circt::firrtl::getModulePortInfo().
verifyModuleSignature()
static LogicalResult verifyModuleSignature (Operation * op) static
Definition at line 482 of file FIRRTLOps.cpp.
References circt::firrtl::getModuleType().
Referenced by verifyFExtModuleOp(), and verifyFModuleOp().
verifyRTLStructCastOp()
static LogicalResult verifyRTLStructCastOp (RTLStructCastOp cast) static
Definition at line 1471 of file FIRRTLOps.cpp.
References circt::rtl::getBitWidth(), circt::firrtl::BundleType::getElements(), and circt::firrtl::getPassiveType().
verifyStdIntCastOp()
static LogicalResult verifyStdIntCastOp (StdIntCastOp cast) static
Definition at line 1402 of file FIRRTLOps.cpp.
References circt::firrtl::FIRRTLType::getBitWidthOrSentinel().