CIRCT: lib/Dialect/FIRRTL/FIRRTLTypes.cpp File Reference
FIRRTLTypes.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
Classes
struct circt::firrtl::detail::WidthTypeStorage
struct circt::firrtl::detail::FlipTypeStorage
struct circt::firrtl::detail::BundleTypeStorage
struct circt::firrtl::detail::VectorTypeStorage
Namespaces
circt
circt::firrtl
circt::firrtl::detail
Enumerations
enum { IsPassiveBitMask = 0x1, ContainsAnalogBitMask = 0x2 }
Functions
static ParseResult parseType (FIRRTLType &result, DialectAsmParser &parser)
type ::= clock ::= reset ::= asyncreset ::= sint ('<' int '>')? ::= uint ('<' int '>')? ::= analog ('<' int '>')? ::= flip '<' type '>' ::= bundle '<' (bundle-elt (',' bundle-elt)*)? '>' ::= vector '<' type ',' int '>'
static bool areBundleElementsEquivalent (BundleType::BundleElement destElement, BundleType::BundleElement srcElement)
Helper to implement the equivalence logic for a pair of bundle elements.
static Optional< int32_t > getWidthQualifiedTypeWidth (firrtl::detail::WidthTypeStorage *impl)
static FIRRTLType getFlippedBundleType (ArrayRef< BundleType::BundleElement > elements)
Return a bundle type with the specified elements all flipped.
llvm::hash_code circt::firrtl::hash_value (const BundleType::BundleElement &arg)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IsPassiveBitMask
Bit set if the type only contains passive elements.
ContainsAnalogBitMask
Bit set if the type contains an analog type.
Definition at line 577 of file FIRRTLTypes.cpp.
Function Documentation
areBundleElementsEquivalent()
static bool areBundleElementsEquivalent (BundleType::BundleElement destElement, BundleType::BundleElement srcElement) static
Helper to implement the equivalence logic for a pair of bundle elements.
Note that the FIRRTL spec requires bundle elements to have the same orientation, but this only compares their passive types. The FIRRTL dialect differs from the spec in how it uses flip types for module output ports and canonicalizes flips in bundles, so only passive types can be compared here.
Definition at line 320 of file FIRRTLTypes.cpp.
References circt::firrtl::areTypesEquivalent(), circt::firrtl::BundleType::BundleElement::name, and circt::firrtl::BundleType::BundleElement::type.
Referenced by circt::firrtl::areTypesEquivalent().
getFlippedBundleType()
static FIRRTLType getFlippedBundleType (ArrayRef< BundleType::BundleElement > elements) static
Return a bundle type with the specified elements all flipped.
This assumes the elements list is non-empty.
Definition at line 501 of file FIRRTLTypes.cpp.
References circt::firrtl::FlipType::get(), and circt::firrtl::BundleType::get().
Referenced by circt::firrtl::FlipType::get(), and circt::firrtl::BundleType::get().
getWidthQualifiedTypeWidth()
static Optional<int32_t> getWidthQualifiedTypeWidth (firrtl::detail::WidthTypeStorage * impl) static
Definition at line 437 of file FIRRTLTypes.cpp.
References circt::firrtl::detail::WidthTypeStorage::width.
Referenced by circt::firrtl::SIntType::getWidth(), circt::firrtl::UIntType::getWidth(), and circt::firrtl::AnalogType::getWidth().
parseType()
static ParseResult parseType (FIRRTLType & result, DialectAsmParser & parser) static
type ::= clock ::= reset ::= asyncreset ::= sint ('<' int '>')? ::= uint ('<' int '>')? ::= analog ('<' int '>')? ::= flip '<' type '>' ::= bundle '<' (bundle-elt (',' bundle-elt)*)? '>' ::= vector '<' type ',' int '>'
bundle-elt ::= identifier ':' type
Definition at line 88 of file FIRRTLTypes.cpp.
References circt::firrtl::BundleType::get(), and circt::firrtl::FVectorType::get().
Referenced by filterUselessName(), circt::rtl::RTLDialect::getDialectNamespace(), circt::sv::SVDialect::getDialectNamespace(), circt::llhd::LLHDDialect::getDialectNamespace(), and circt::firrtl::FIRRTLDialect::parseType().