CIRCT: lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp File Reference
HandshakeToFIRRTL.cpp File Reference
#include "circt/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/Visitor.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/MathExtras.h"
Classes
struct HandshakeFuncOpLowering
Process of lowering:
Macros
#define HANDLE(OPTYPE, FIRRTLTYPE) bool visitStdExpr(OPTYPE op) { return buildBinaryLogic<FIRRTLTYPE>(), true; }
Typedefs
using ValueVector = llvm::SmallVector< Value, 3 >
using ValueVectorList = std::vector< ValueVector >
Functions
static void legalizeFModule (FModuleOp moduleOp)
static FIRRTLType getFIRRTLType (Type type)
Get the corresponding FIRRTL type given the built-in data type.
static FIRRTLType getBundleType (Type type, bool isFlip)
Return a FIRRTL bundle type (with data, valid, and ready subfields) given a standard data type.
static Value createConstantOp (FIRRTLType opType, APInt value, Location insertLoc, ConversionPatternRewriter &rewriter)
static Type getHandshakeDataType (Operation *op)
static std::string getSubModuleName (Operation *oldOp)
Construct a name for creating FIRRTL sub-module.
static size_t getNumIndexBits (uint64_t numValues)
Return the number of bits needed to index the given number of values.
static Value createMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a binary-encoded select value.
static Value createOneHotMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a one-hot select value.
static Value createDecoder (Value input, unsigned width, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct a decoder by dynamically shifting 1 bit by the input amount.
static Value createPriorityArbiter (ArrayRef< Value > inputs, Value defaultValue, DenseMap< size_t, Value > &indexMapping, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct an arbiter based on a simple priority-encoding scheme.
static void createMergeArgReady (ArrayRef< Value > outputs, Value fired, Value winner, Value defaultValue, DenseMap< size_t, Value > &indexMappings, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct the logic to assign the ready outputs for ControlMergeOp and MergeOp.
static void extractValues (ArrayRef< ValueVector *> valueVectors, size_t index, SmallVectorImpl< Value > &result)
static FModuleOp createTopModuleOp (handshake::FuncOp funcOp, unsigned numClocks, ConversionPatternRewriter &rewriter)
Currently we are not considering clock and registers, thus the generated circuit is pure combinational logic.
static FModuleOp checkSubModuleOp (FModuleOp topModuleOp, Operation *oldOp)
Check whether a submodule with the same name has been created elsewhere.
static FModuleOp createSubModuleOp (FModuleOp topModuleOp, Operation *oldOp, bool hasClock, ConversionPatternRewriter &rewriter)
All standard expressions and handshake elastic components will be converted to a FIRRTL sub-module and be instantiated in the top-module.
static ValueVectorList extractSubfields (FModuleOp subModuleOp, Location insertLoc, ConversionPatternRewriter &rewriter)
Extract all subfields of all ports of the sub-module.
static void createInstOp (Operation *oldOp, FModuleOp subModuleOp, FModuleOp topModuleOp, unsigned clockDomain, ConversionPatternRewriter &rewriter)
Create InstanceOp in the top-module.
static void convertReturnOp (Operation *oldOp, FModuleOp topModuleOp, handshake::FuncOp funcOp, ConversionPatternRewriter &rewriter)
Macro Definition Documentation
HANDLE
#define HANDLE (OPTYPE, FIRRTLTYPE) bool visitStdExpr(OPTYPE op) { return buildBinaryLogic<FIRRTLTYPE>(), true; }
Definition at line 590 of file HandshakeToFIRRTL.cpp.
Typedef Documentation
ValueVector
using ValueVector = llvm::SmallVector<Value, 3>
Definition at line 28 of file HandshakeToFIRRTL.cpp.
ValueVectorList
using ValueVectorList = std::vector<ValueVector>
Definition at line 29 of file HandshakeToFIRRTL.cpp.
Function Documentation
checkSubModuleOp()
static FModuleOp checkSubModuleOp (FModuleOp topModuleOp, Operation * oldOp) static
Check whether a submodule with the same name has been created elsewhere.
Return the matched submodule if true, otherwise return nullptr.
Definition at line 486 of file HandshakeToFIRRTL.cpp.
References getSubModuleName().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
convertReturnOp()
static void convertReturnOp (Operation * oldOp, FModuleOp topModuleOp, handshake::FuncOp funcOp, ConversionPatternRewriter & rewriter) static
Definition at line 1983 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createConstantOp()
static Value createConstantOp (FIRRTLType opType, APInt value, Location insertLoc, ConversionPatternRewriter & rewriter) static
Definition at line 107 of file HandshakeToFIRRTL.cpp.
Referenced by createOneHotMuxTree(), and createPriorityArbiter().
createDecoder()
static Value createDecoder (Value input, unsigned width, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct a decoder by dynamically shifting 1 bit by the input amount.
See http://www.imm.dtu.dk/~masca/chisel-book.pdf Section 5.2.
Definition at line 314 of file HandshakeToFIRRTL.cpp.
createInstOp()
static void createInstOp (Operation * oldOp, FModuleOp subModuleOp, FModuleOp topModuleOp, unsigned clockDomain, ConversionPatternRewriter & rewriter) static
Create InstanceOp in the top-module.
This will be called after the corresponding sub-module and combinational logic are created.
Definition at line 1931 of file HandshakeToFIRRTL.cpp.
References circt::firrtl::getModulePortInfo().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createMergeArgReady()
static void createMergeArgReady (ArrayRef< Value > outputs, Value fired, Value winner, Value defaultValue, DenseMap< size_t, Value > & indexMappings, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct the logic to assign the ready outputs for ControlMergeOp and MergeOp.
The logic is identical for each output. If the fired value is asserted, and the win value holds the output's index, that output is ready.
Definition at line 366 of file HandshakeToFIRRTL.cpp.
createMuxTree()
static Value createMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a binary-encoded select value.
Definition at line 215 of file HandshakeToFIRRTL.cpp.
References getNumIndexBits().
createOneHotMuxTree()
static Value createOneHotMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a one-hot select value.
Assumes select has a UIntType.
Definition at line 281 of file HandshakeToFIRRTL.cpp.
References createConstantOp(), and circt::firrtl::FIRRTLType::getBitWidthOrSentinel().
createPriorityArbiter()
static Value createPriorityArbiter (ArrayRef< Value > inputs, Value defaultValue, DenseMap< size_t, Value > & indexMapping, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct an arbiter based on a simple priority-encoding scheme.
In addition to returning the arbiter result, the index for each input is added to a mapping for other lowerings to make use of.
Definition at line 339 of file HandshakeToFIRRTL.cpp.
References createConstantOp().
createSubModuleOp()
static FModuleOp createSubModuleOp (FModuleOp topModuleOp, Operation * oldOp, bool hasClock, ConversionPatternRewriter & rewriter) static
All standard expressions and handshake elastic components will be converted to a FIRRTL sub-module and be instantiated in the top-module.
Definition at line 499 of file HandshakeToFIRRTL.cpp.
References getBundleType(), and getSubModuleName().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createTopModuleOp()
static FModuleOp createTopModuleOp (handshake::FuncOp funcOp, unsigned numClocks, ConversionPatternRewriter & rewriter) static
Currently we are not considering clock and registers, thus the generated circuit is pure combinational logic.
If graph cycle exists, at least one buffer is required to be inserted for breaking the cycle, which will be supported in the next patch.
Definition at line 402 of file HandshakeToFIRRTL.cpp.
References getBundleType().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
extractSubfields()
static ValueVectorList extractSubfields (FModuleOp subModuleOp, Location insertLoc, ConversionPatternRewriter & rewriter) static
Extract all subfields of all ports of the sub-module.
Definition at line 546 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
extractValues()
static void extractValues (ArrayRef< ValueVector *> valueVectors, size_t index, SmallVectorImpl< Value > & result) static
Definition at line 388 of file HandshakeToFIRRTL.cpp.
getBundleType()
static FIRRTLType getBundleType (Type type, bool isFlip) static
Return a FIRRTL bundle type (with data, valid, and ready subfields) given a standard data type.
Definition at line 72 of file HandshakeToFIRRTL.cpp.
References getFIRRTLType().
Referenced by createSubModuleOp(), and createTopModuleOp().
getFIRRTLType()
static FIRRTLType getFIRRTLType (Type type) static
Get the corresponding FIRRTL type given the built-in data type.
Current supported data types are integer (signed, unsigned, and signless), index, and none.
Definition at line 45 of file HandshakeToFIRRTL.cpp.
Referenced by getBundleType().
getHandshakeDataType()
static Type getHandshakeDataType (Operation * op) static
Definition at line 120 of file HandshakeToFIRRTL.cpp.
Referenced by getSubModuleName().
getNumIndexBits()
static size_t getNumIndexBits (uint64_t numValues) static
Return the number of bits needed to index the given number of values.
Definition at line 209 of file HandshakeToFIRRTL.cpp.
Referenced by createMuxTree().
getSubModuleName()
static std::string getSubModuleName (Operation * oldOp) static
Construct a name for creating FIRRTL sub-module.
Definition at line 142 of file HandshakeToFIRRTL.cpp.
References getHandshakeDataType().
Referenced by checkSubModuleOp(), and createSubModuleOp().
legalizeFModule()
static void legalizeFModule (FModuleOp moduleOp) static
Definition at line 35 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().