CIRCT: lib/Dialect/Handshake/HandshakeOps.cpp File Reference
HandshakeOps.cpp File Reference
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Value.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/Any.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/Support/Debug.h"
#include "circt/Dialect/Handshake/HandshakeOps.inc"
#include "circt/Dialect/Handshake/HandshakeOps.cpp.inc"
#include "circt/Dialect/Handshake/HandshakeInterfaces.cpp.inc"
Namespaces
circt
circt::handshake
Macros
#define INDEX_WIDTH 32
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
std::vector< mlir::Value > toVector (mlir::ValueRange range)
bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
std::vector< llvm::Any > fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
void storeValues (std::vector< llvm::Any > &values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > &timeMap, double latency)
bool tryToExecute (Operation *op, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< mlir::Value > &scheduleList, double latency)
static LogicalResult verify (MuxOp op)
static ParseResult parseReturnOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, handshake::ReturnOp op)
static LogicalResult verify (handshake::ReturnOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 867 of file HandshakeOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
INDEX_WIDTH
#define INDEX_WIDTH 32
Definition at line 37 of file HandshakeOps.cpp.
Referenced by verify().
Function Documentation
fetchValues()
std::vector<llvm::Any> fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap)
Definition at line 66 of file HandshakeOps.cpp.
Referenced by tryToExecute().
isReadyToExecute()
bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap)
Definition at line 51 of file HandshakeOps.cpp.
Referenced by tryToExecute().
parseReturnOp()
static ParseResult parseReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 817 of file HandshakeOps.cpp.
print()
static void print (OpAsmPrinter & p, handshake::ReturnOp op) static
Definition at line 826 of file HandshakeOps.cpp.
storeValues()
void storeValues (std::vector< llvm::Any > & values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap)
Definition at line 78 of file HandshakeOps.cpp.
Referenced by tryToExecute().
toVector()
std::vector<mlir::Value> toVector (mlir::ValueRange range)
Definition at line 46 of file HandshakeOps.cpp.
Referenced by tryToExecute(), and verify().
tryToExecute()
bool tryToExecute (Operation * op, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap, llvm::DenseMap< mlir::Value, double > & timeMap, std::vector< mlir::Value > & scheduleList, double latency)
Definition at line 96 of file HandshakeOps.cpp.
References fetchValues(), isReadyToExecute(), storeValues(), toVector(), and updateTime().
Referenced by circt::handshake::HandshakeOpsDialect::HandshakeOpsDialect(), and verify().
updateTime()
void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > & timeMap, double latency)
Definition at line 86 of file HandshakeOps.cpp.
Referenced by tryToExecute().
verify() [1/2]
static LogicalResult verify (MuxOp op) static
Definition at line 280 of file HandshakeOps.cpp.
References INDEX_WIDTH, toVector(), and tryToExecute().
verify() [2/2]
static LogicalResult verify (handshake::ReturnOp op) static
Definition at line 836 of file HandshakeOps.cpp.