CIRCT: lib/Dialect/LLHD/IR/LLHDDialect.cpp File Reference
LLHDDialect.cpp File Reference
#include "circt/Dialect/LLHD/IR/LLHDDialect.h"
#include "circt/Dialect/LLHD/IR/LLHDOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "circt/Dialect/LLHD/IR/LLHD.cpp.inc"
Classes
struct circt::llhd::detail::SigTypeStorage
Storage struct implementation for LLHD's sig type.
struct circt::llhd::detail::ArrayTypeStorage
Array Type Storage and Uniquing.
struct circt::llhd::detail::PtrTypeStorage
struct circt::llhd::detail::TimeAttrStorage
Namespaces
circt
circt::llhd
circt::llhd::detail
Macros
#define GET_OP_LIST
Functions
static Type parseNestedType (DialectAsmParser &parser)
Parse a nested type, enclosed in angle brackts (<...>).
static Type parseSigType (DialectAsmParser &parser)
Parse a signal type.
static Type parsePtrType (DialectAsmParser &parser)
Parse a pointer type.
static Type parseArrayType (DialectAsmParser &parser)
Parse an array type.
static void printSigType (SigType sig, DialectAsmPrinter &printer)
Print a signal type with custom syntax: type ::= !sig.type<underlying-type>
static Attribute parseTimeAttribute (DialectAsmParser &parser, Type type)
Parse a time attribute with the custom syntax: time ::= #llhd.time<time time_unit, delta d, epsilon e>
static void printTimeAttribute (TimeAttr attr, DialectAsmPrinter &printer)
Print an LLHD time attribute.
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseArrayType()
static Type parseArrayType (DialectAsmParser & parser) static
Parse an array type.
Syntax: array ::= !llhd.array<{length}x{elementType}>
Definition at line 111 of file LLHDDialect.cpp.
References circt::llhd::ArrayType::get().
Referenced by circt::llhd::LLHDDialect::parseType().
parseNestedType()
static Type parseNestedType (DialectAsmParser & parser) static
Parse a nested type, enclosed in angle brackts (<...>).
Definition at line 79 of file LLHDDialect.cpp.
Referenced by parsePtrType(), and parseSigType().
parsePtrType()
static Type parsePtrType (DialectAsmParser & parser) static
Parse a pointer type.
Syntax: ptr ::= !llhd.ptr<type
Definition at line 105 of file LLHDDialect.cpp.
References circt::llhd::PtrType::get(), and parseNestedType().
Referenced by circt::llhd::LLHDDialect::parseType().
parseSigType()
static Type parseSigType (DialectAsmParser & parser) static
Parse a signal type.
Syntax: sig ::= !llhd.sig<type>
Definition at line 99 of file LLHDDialect.cpp.
References circt::llhd::SigType::get(), and parseNestedType().
Referenced by circt::llhd::LLHDDialect::parseType().
parseTimeAttribute()
static Attribute parseTimeAttribute (DialectAsmParser & parser, Type type) static
Parse a time attribute with the custom syntax: time ::= #llhd.time<time time_unit, delta d, epsilon e>
Definition at line 180 of file LLHDDialect.cpp.
References circt::llhd::TimeAttr::get().
Referenced by circt::llhd::LLHDDialect::parseAttribute().
printSigType()
static void printSigType (SigType sig, DialectAsmPrinter & printer) static
Print a signal type with custom syntax: type ::= !sig.type<underlying-type>
Definition at line 155 of file LLHDDialect.cpp.
References circt::llhd::SigType::getKeyword(), and circt::llhd::SigType::getUnderlyingType().
Referenced by circt::llhd::LLHDDialect::printType().
printTimeAttribute()
static void printTimeAttribute (TimeAttr attr, DialectAsmPrinter & printer) static
Print an LLHD time attribute.
Definition at line 233 of file LLHDDialect.cpp.
References circt::llhd::TimeAttr::getDelta(), circt::llhd::TimeAttr::getEps(), circt::llhd::TimeAttr::getKeyword(), circt::llhd::TimeAttr::getTime(), and circt::llhd::TimeAttr::getTimeUnit().
Referenced by circt::llhd::LLHDDialect::printAttribute().