CIRCT: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp File Reference
LowerTypes.cpp File Reference
#include "./PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/ImplicitLocOpBuilder.h"
#include "llvm/ADT/StringSwitch.h"
Functions
static void flattenBundleTypes (FIRRTLType type, StringRef suffixSoFar, bool isFlipped, SmallVectorImpl< FlatBundleFieldEntry > &results)
static BundleType getCanonicalBundleType (Type originalType)
static DictionaryAttr getArgAttrs (StringAttr nameAttr, StringRef suffix, OpBuilder *builder)
Function Documentation
flattenBundleTypes()
static void flattenBundleTypes (FIRRTLType type, StringRef suffixSoFar, bool isFlipped, SmallVectorImpl< FlatBundleFieldEntry > & results) static
Definition at line 40 of file LowerTypes.cpp.
Referenced by circt::firrtl::createLowerFIRRTLTypesPass(), and getArgAttrs().
getArgAttrs()
static DictionaryAttr getArgAttrs (StringAttr nameAttr, StringRef suffix, OpBuilder * builder) static
Definition at line 449 of file LowerTypes.cpp.
References flattenBundleTypes(), getCanonicalBundleType(), and circt::firrtl::getFIRRTLNameAttr().
Referenced by circt::firrtl::getFIRRTLNameAttr(), circt::rtl::getModulePortInfo(), circt::firrtl::getModulePortInfo(), printFunctionSignature2(), printModuleSignature(), and printProcArguments().
getCanonicalBundleType()
static BundleType getCanonicalBundleType (Type originalType) static
Definition at line 70 of file LowerTypes.cpp.
References circt::firrtl::BundleType::getElementType().
Referenced by circt::firrtl::createLowerFIRRTLTypesPass(), and getArgAttrs().