CIRCT: lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp File Reference
LowerToRTL.cpp File Reference
#include "../PassDetail.h"
#include "circt/Conversion/FIRRTLToRTL/FIRRTLToRTL.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/RTL/RTLOps.h"
#include "circt/Dialect/RTL/RTLTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/ImplicitLocOpBuilder.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/TinyPtrVector.h"
Functions
static Type lowerType (Type type)
Given a FIRRTL type, return the corresponding type for the RTL dialect.
static IntType getWidestIntType (Type t1, Type t2)
Given two FIRRTL integer types, return the widest one.
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a standard type to a FIRRTL type, potentially with a flip.
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a FIRRTL type (potentially with a flip) to a standard type.
static bool isZeroBitFIRRTLType (Type type)
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
static bool collectOperationTreeBelowMarker (Value value, Operation *marker, SmallVector< Operation *, 8 > &ops, SmallPtrSet< Operation *, 8 > &visited)
If the value dominates the marker, just return.
static Value tryEliminatingConnectsToValue (Value flipValue, Operation *insertPoint)
Given a value of flip type, check to see if all of the uses of it are connects.
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn)
Zero bit operands end up looking like failures from getLoweredValue.
static bool flattenBundleTypes (Type type, StringRef nameSoFar, SmallVectorImpl< FlatBundleFieldEntry > &results)
Convert a nested bundle of fields into a flat list of fields.
Function Documentation
castFromFIRRTLType()
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a FIRRTL type (potentially with a flip) to a standard type.
Definition at line 83 of file LowerToRTL.cpp.
References circt::ImplicitLocOpBuilder::createOrFold().
Referenced by tryEliminatingConnectsToValue().
castToFIRRTLType()
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a standard type to a FIRRTL type, potentially with a flip.
Definition at line 62 of file LowerToRTL.cpp.
References circt::ImplicitLocOpBuilder::createOrFold().
Referenced by tryEliminatingConnectsToValue().
collectOperationTreeBelowMarker()
static bool collectOperationTreeBelowMarker (Value value, Operation * marker, SmallVector< Operation *, 8 > & ops, SmallPtrSet< Operation *, 8 > & visited) static
If the value dominates the marker, just return.
Otherwise add it to ops and recursively process its operands.
Return true if we can't move an operation, false otherwise.
Definition at line 357 of file LowerToRTL.cpp.
Referenced by tryEliminatingConnectsToValue().
flattenBundleTypes()
static bool flattenBundleTypes (Type type, StringRef nameSoFar, SmallVectorImpl< FlatBundleFieldEntry > & results) static
Convert a nested bundle of fields into a flat list of fields.
This is used when working with mems to flatten them. Return true if we fail to lower any of the element types, or false if successul.
Definition at line 1341 of file LowerToRTL.cpp.
References circt::firrtl::UIntType::get(), circt::sv::getAnyRTLArrayElementType(), circt::sv::getInOutElementType(), circt::firrtl::getPassiveType(), getWidestIntType(), handleZeroBit(), circt::firrtl::IntType::hasWidth(), circt::firrtl::IntType::isSigned(), isZeroBitFIRRTLType(), and lowerType().
getWidestIntType()
static IntType getWidestIntType (Type t1, Type t2) static
Given two FIRRTL integer types, return the widest one.
Definition at line 56 of file LowerToRTL.cpp.
References circt::firrtl::IntType::getWidth().
Referenced by flattenBundleTypes().
handleZeroBit()
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn) static
Zero bit operands end up looking like failures from getLoweredValue.
This helper function invokes the closure specified if the operand was actually zero bit, or returns failure() if it was some other kind of failure.
Definition at line 964 of file LowerToRTL.cpp.
References getBitWidthOrSentinel(), circt::firrtl::getPassiveType(), circt::firrtl::isExpression(), circt::firrtl::IntType::isSigned(), isZeroBitFIRRTLType(), and lowerType().
Referenced by flattenBundleTypes().
isZeroBitFIRRTLType()
static bool isZeroBitFIRRTLType (Type type) static
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
Definition at line 94 of file LowerToRTL.cpp.
References circt::firrtl::getPassiveType().
Referenced by flattenBundleTypes(), and handleZeroBit().
lowerType()
static Type lowerType (Type type) static
Given a FIRRTL type, return the corresponding type for the RTL dialect.
This returns a null type if it cannot be lowered.
Definition at line 29 of file LowerToRTL.cpp.
References circt::firrtl::FIRRTLType::getPassiveType().
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass(), flattenBundleTypes(), handleZeroBit(), and tryEliminatingConnectsToValue().
tryEliminatingConnectsToValue()
static Value tryEliminatingConnectsToValue (Value flipValue, Operation * insertPoint) static
Given a value of flip type, check to see if all of the uses of it are connects.
If so, remove the connects and return the value being connected to it, converted to an RTL type. If this isn't a situation we can handle, just return null.
This can happen when there are no connects to the value, or if firrtl.invalid is used. The 'mergePoint' location is where a 'rtl.merge' operation should be inserted if needed.
Definition at line 398 of file LowerToRTL.cpp.
References castFromFIRRTLType(), castToFIRRTLType(), collectOperationTreeBelowMarker(), circt::ImplicitLocOpBuilder::create(), circt::ImplicitLocOpBuilder::createOrFold(), circt::firrtl::FlipType::get(), getBitWidthOrSentinel(), circt::firrtl::getModulePortInfo(), circt::firrtl::getPassiveType(), and lowerType().