CIRCT: circt::llhd Namespace Reference
circt::llhd Namespace Reference
Namespaces
detail
sim
Classes
class ArrayType
class LLHDDialect
class PtrType
class SigType
struct TemporalRegionAnalysis
class TimeAttr
class TimeType
Functions
std::unique_ptr< OperationPass< ModuleOp > > createConvertFIRRTLToLLHDPass ()
Create a FIRRTL to LLHD conversion pass.
void registerFIRRTLToLLHDPasses ()
void populateLLHDToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns, size_t &sigCounter, size_t &regCounter)
Get the LLHD to LLVM conversion patterns.
std::unique_ptr< OperationPass< ModuleOp > > createConvertLLHDToLLVMPass ()
Create an LLHD to LLVM conversion pass.
void initLLHDToLLVMPass ()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > createConvertRTLToLLHDPass ()
Create a RTL to LLHD conversion pass.
void registerRTLToLLHDPasses ()
unsigned getLLHDTypeWidth (Type type)
std::unique_ptr< OperationPass< ModuleOp > > createProcessLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createFunctionEliminationPass ()
std::unique_ptr< OperationPass< ProcOp > > createMemoryToBlockArgumentPass ()
std::unique_ptr< OperationPass< ProcOp > > createEarlyCodeMotionPass ()
void initLLHDTransformationPasses ()
Register the LLHD Transformation passes.
mlir::LogicalResult exportVerilog (mlir::ModuleOp module, llvm::raw_ostream &os)
void registerToVerilogTranslation ()
Function Documentation
createConvertFIRRTLToLLHDPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::llhd::createConvertFIRRTLToLLHDPass ()
Create a FIRRTL to LLHD conversion pass.
Definition at line 68 of file FIRRTLToLLHD.cpp.
References circt::llhd::SigType::get(), circt::llhd::TimeType::get(), circt::llhd::TimeAttr::get(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), and circt::firrtl::getPassiveType().
createConvertLLHDToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::llhd::createConvertLLHDToLLVMPass ()
Create an LLHD to LLVM conversion pass.
Definition at line 2801 of file LLHDToLLVM.cpp.
createConvertRTLToLLHDPass()
std::unique_ptr< OperationPass< mlir::ModuleOp > > circt::llhd::createConvertRTLToLLHDPass ()
Create a RTL to LLHD conversion pass.
Definition at line 51 of file RTLToLLHD.cpp.
createEarlyCodeMotionPass()
std::unique_ptr< OperationPass< llhd::ProcOp > > circt::llhd::createEarlyCodeMotionPass ()
Definition at line 134 of file EarlyCodeMotionPass.cpp.
createFunctionEliminationPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::llhd::createFunctionEliminationPass ()
Definition at line 53 of file FunctionEliminationPass.cpp.
createMemoryToBlockArgumentPass()
std::unique_ptr< OperationPass< llhd::ProcOp > > circt::llhd::createMemoryToBlockArgumentPass ()
Definition at line 242 of file MemoryToBlockArgumentPass.cpp.
createProcessLoweringPass()
std::unique_ptr< OperationPass< ModuleOp > > circt::llhd::createProcessLoweringPass ()
Definition at line 137 of file ProcessLoweringPass.cpp.
exportVerilog()
mlir::LogicalResult circt::llhd::exportVerilog (mlir::ModuleOp module, llvm::raw_ostream & os)
Referenced by mlirExportVerilog(), and registerToVerilogTranslation().
getLLHDTypeWidth()
unsigned circt::llhd::getLLHDTypeWidth (Type type)
Definition at line 134 of file LLHDOps.cpp.
initLLHDToLLVMPass()
void circt::llhd::initLLHDToLLVMPass ()
Definition at line 2811 of file LLHDToLLVM.cpp.
Referenced by circt::registerAllConversionPasses().
initLLHDTransformationPasses()
void circt::llhd::initLLHDTransformationPasses ()
Register the LLHD Transformation passes.
Definition at line 20 of file PassRegistration.cpp.
Referenced by circt::registerAllPasses().
populateLLHDToLLVMConversionPatterns()
void circt::llhd::populateLLHDToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns, size_t & sigCounter, size_t & regCounter)
Get the LLHD to LLVM conversion patterns.
Definition at line 2710 of file LLHDToLLVM.cpp.
References convertArrayType(), convertPtrType(), convertSigType(), convertTimeType(), and convertTupleType().
registerFIRRTLToLLHDPasses()
void circt::llhd::registerFIRRTLToLLHDPasses ()
Definition at line 276 of file FIRRTLToLLHD.cpp.
Referenced by circt::registerAllConversionPasses().
registerRTLToLLHDPasses()
void circt::llhd::registerRTLToLLHDPasses ()
Definition at line 61 of file RTLToLLHD.cpp.
References circt::llhd::SigType::get().
Referenced by circt::registerAllConversionPasses().
registerToVerilogTranslation()
void circt::llhd::registerToVerilogTranslation ()
Definition at line 422 of file TranslateToVerilog.cpp.
References exportVerilog().
Referenced by circt::registerAllTranslations().