CIRCT: circt::firrtl Namespace Reference
circt::firrtl Namespace Reference
Namespaces
detail
Classes
class AnalogType
class AsyncResetType
firrtl.AsyncReset.
class BundleType
BundleType is an aggregate of named elements.
class ClockType
firrtl.Clock describe wires and ports meant for carrying clock signals.
class DeclVisitor
ExprVisitor is a visitor for FIRRTL declaration nodes.
class ExprVisitor
ExprVisitor is a visitor for FIRRTL expression nodes.
class FIRLexer
This implements a lexer for .fir files.
struct FIRParserOptions
class FIRRTLDialect
class FIRRTLType
class FIRRTLVisitor
FIRRTLVisitor allows you to visit all of the expr/stmt/decls with one class declaration.
class FIRToken
This represents a specific token for .fir files.
class FlipType
class FVectorType
VectorType is a fixed size collection of elements, like an array.
class IntType
This is the common base class between SIntType and UIntType.
struct ModulePortInfo
This holds the name and type that describes the module's ports.
class ResetType
firrtl.Reset.
class SIntType
A signed integer type, whose width may not be known.
class StmtVisitor
ExprVisitor is a visitor for FIRRTL statement nodes.
class UIntType
An unsigned integer type, whose width may not be known.
class WidthQualifiedType
Functions
std::unique_ptr< mlir::Pass > createLowerFIRRTLToRTLModulePass ()
This is the pass constructor.
std::unique_ptr< mlir::Pass > createLowerFIRRTLToRTLPass ()
This is the pass constructor.
mlir::OwningModuleRef importFIRRTL (llvm::SourceMgr &sourceMgr, mlir::MLIRContext *context, FIRParserOptions options={})
void registerFromFIRRTLTranslation ()
StringAttr getFIRRTLNameAttr (ArrayRef< NamedAttribute > attrs)
If the specified attribute list has a firrtl.name attribute, return its value.
bool isExpression (Operation *op)
Return true if the specified operation is a firrtl expression.
FunctionType getModuleType (Operation *op)
Return the function type that corresponds to a module.
void getModulePortInfo (Operation *op, SmallVectorImpl< ModulePortInfo > &results)
This function can extract information about ports from a module and an extmodule.
bool areTypesEquivalent (FIRRTLType destType, FIRRTLType srcType)
Returns whether the two types are equivalent.
mlir::Type getArrayElementType (mlir::Type array)
mlir::Type getPassiveType (mlir::Type anyFIRRTLType)
std::unique_ptr< mlir::Pass > createLowerFIRRTLTypesPass ()
This is the pass constructor.
llvm::hash_code hash_value (const BundleType::BundleElement &arg)
Function Documentation
areTypesEquivalent()
bool circt::firrtl::areTypesEquivalent (FIRRTLType destType, FIRRTLType srcType)
Returns whether the two types are equivalent.
See the FIRRTL spec for the full definition of type equivalence. This predicate differs from the spec in that it only compares passive types. Because of how the FIRRTL dialect uses flip types in module ports and aggregates, this definition, unlike the spec, ignores flips.
Definition at line 333 of file FIRRTLTypes.cpp.
References areBundleElementsEquivalent(), getArrayElementType(), circt::firrtl::BundleType::getElements(), circt::firrtl::FVectorType::getElementType(), circt::firrtl::FVectorType::getNumElements(), circt::firrtl::FIRRTLType::getPassiveType(), getPassiveType(), circt::firrtl::FIRRTLType::getWidthlessType(), circt::firrtl::FIRRTLType::isPassive(), and circt::firrtl::FIRRTLType::isResetType().
Referenced by areBundleElementsEquivalent(), circt::firrtl::FIRRTLType::classof(), and verifyConnectOp().
createLowerFIRRTLToRTLModulePass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerFIRRTLToRTLModulePass ()
This is the pass constructor.
Definition at line 126 of file LowerToRTL.cpp.
References circt::rtl::ModulePortInfo::argNum, circt::ImplicitLocOpBuilder::create(), circt::rtl::ModulePortInfo::direction, circt::rtl::INOUT, circt::rtl::INPUT, lowerType(), circt::rtl::ModulePortInfo::name, circt::rtl::OUTPUT, and circt::rtl::ModulePortInfo::type.
createLowerFIRRTLToRTLPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerFIRRTLToRTLPass ()
This is the pass constructor.
Definition at line 903 of file LowerToRTL.cpp.
References circt::ImplicitLocOpBuilder::setLoc().
createLowerFIRRTLTypesPass()
std::unique_ptr< mlir::Pass > circt::firrtl::createLowerFIRRTLTypesPass ()
This is the pass constructor.
Definition at line 126 of file LowerTypes.cpp.
References flattenBundleTypes(), circt::firrtl::FlipType::get(), getCanonicalBundleType(), circt::firrtl::BundleType::getElements(), and getPassiveType().
getArrayElementType()
mlir::Type circt::firrtl::getArrayElementType (mlir::Type array)
Referenced by areTypesEquivalent(), and circt::firrtl::FIRRTLType::classof().
getFIRRTLNameAttr()
StringAttr circt::firrtl::getFIRRTLNameAttr (ArrayRef< NamedAttribute > attrs)
If the specified attribute list has a firrtl.name attribute, return its value.
Definition at line 25 of file FIRRTLDialect.cpp.
References getArgAttrs().
Referenced by getArgAttrs(), circt::firrtl::FIRRTLDialect::getDialectNamespace(), getModulePortInfo(), and printFunctionSignature2().
getModulePortInfo()
void circt::firrtl::getModulePortInfo (Operation * op, SmallVectorImpl< ModulePortInfo > & results)
This function can extract information about ports from a module and an extmodule.
Definition at line 234 of file FIRRTLOps.cpp.
References getArgAttrs(), getFIRRTLNameAttr(), and getModuleType().
Referenced by createInstOp(), emitBeginEndRegion(), circt::firrtl::ModulePortInfo::isInOut(), tryEliminatingConnectsToValue(), and verifyInstanceOp().
getModuleType()
FunctionType circt::firrtl::getModuleType (Operation * op)
Return the function type that corresponds to a module.
Definition at line 227 of file FIRRTLOps.cpp.
Referenced by getModulePortInfo(), circt::firrtl::ModulePortInfo::isInOut(), printModuleLikeOp(), and verifyModuleSignature().
getPassiveType()
mlir::Type circt::firrtl::getPassiveType (mlir::Type anyFIRRTLType)
Referenced by areTypesEquivalent(), circt::firrtl::FIRRTLType::classof(), circt::firrtl::FIRRTLType::containsAnalog(), circt::llhd::createConvertFIRRTLToLLHDPass(), createLowerFIRRTLTypesPass(), flattenBundleTypes(), circt::firrtl::BundleType::getNumElements(), handleZeroBit(), isZeroBitFIRRTLType(), tryEliminatingConnectsToValue(), verifyConnectOp(), and verifyRTLStructCastOp().
hash_value()
llvm::hash_code circt::firrtl::hash_value (const BundleType::BundleElement & arg)
Definition at line 571 of file FIRRTLTypes.cpp.
References circt::firrtl::BundleType::BundleElement::name, and circt::firrtl::BundleType::BundleElement::type.
Referenced by llvm::DenseMapInfo< circt::firrtl::FIRRTLType >::getHashValue().
importFIRRTL()
mlir::OwningModuleRef circt::firrtl::importFIRRTL (llvm::SourceMgr & sourceMgr, mlir::MLIRContext * context, FIRParserOptions options = {})
Referenced by registerFromFIRRTLTranslation().
isExpression()
bool circt::firrtl::isExpression (Operation * op)
Return true if the specified operation is a firrtl expression.
Definition at line 819 of file FIRRTLOps.cpp.
References circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchExprVisitor().
Referenced by handleZeroBit(), and isVerilogExpression().
registerFromFIRRTLTranslation()
void circt::firrtl::registerFromFIRRTLTranslation ()
Definition at line 2648 of file FIRParser.cpp.
References importFIRRTL().
Referenced by circt::registerAllTranslations().