CIRCT: circt Namespace Reference
circt Namespace Reference
Namespaces
esi
firrtl
handshake
llhd
rtl
staticlogic
sv
Classes
class Backedge
Backedge is a wrapper class around a Value.
class BackedgeBuilder
Instantiate one of these and use it to build typed backedges.
class ImplicitLocOpBuilder
ImplictLocOpBuilder maintains a 'current location', allowing use of the create<> method without specifying the location.
Typedefs
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>>
using DenseMap = llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>>
using DenseSet = llvm::DenseSet< ValueT, ValueInfoT >
template<typename Fn >
using function_ref = llvm::function_ref< Fn >
Functions
void registerAllDialects (mlir::DialectRegistry &registry)
void registerAllConversionPasses ()
void registerAllPasses ()
void registerAllTranslations ()
mlir::LogicalResult exportVerilog (mlir::ModuleOp module, llvm::raw_ostream &os)
Export a module containing RTL, and SV dialect code.
void registerToVerilogTranslation ()
Register a translation for exporting FIRRTL, RTL, and SV.
mlir::LogicalResult exportFIRRTLToVerilog (mlir::ModuleOp module, llvm::raw_ostream &os)
Export a module containing RTL, and SV dialect code.
void registerFIRRTLToVerilogTranslation ()
Register a translation for exporting FIRRTL, RTL, and SV.
Typedef Documentation
DenseMap
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> using circt::DenseMap = typedef llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 40 of file LLVM.h.
DenseSet
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>> using circt::DenseSet = typedef llvm::DenseSet<ValueT, ValueInfoT>
Definition at line 42 of file LLVM.h.
function_ref
template<typename Fn > using circt::function_ref = typedef llvm::function_ref<Fn>
Definition at line 44 of file LLVM.h.
Function Documentation
exportFIRRTLToVerilog()
mlir::LogicalResult circt::exportFIRRTLToVerilog (mlir::ModuleOp module, llvm::raw_ostream & os)
Export a module containing RTL, and SV dialect code.
Referenced by emitConditionStmtKind(), and registerFIRRTLToVerilogTranslation().
exportVerilog()
mlir::LogicalResult circt::exportVerilog (mlir::ModuleOp module, llvm::raw_ostream & os)
Export a module containing RTL, and SV dialect code.
Referenced by printArraySubscripts(), and registerToVerilogTranslation().
registerAllConversionPasses()
void circt::registerAllConversionPasses () inline
Definition at line 31 of file InitAllPasses.h.
References circt::llhd::initLLHDToLLVMPass(), circt::llhd::registerFIRRTLToLLHDPasses(), circt::handshake::registerHandshakeToFIRRTLPasses(), circt::llhd::registerRTLToLLHDPasses(), circt::handshake::registerStandardToHandshakePasses(), and circt::staticlogic::registerStandardToStaticLogicPasses().
Referenced by registerAllPasses().
registerAllDialects()
void circt::registerAllDialects (mlir::DialectRegistry & registry) inline
Definition at line 29 of file InitAllDialects.h.
registerAllPasses()
void circt::registerAllPasses () inline
Definition at line 41 of file InitAllPasses.h.
References circt::llhd::initLLHDTransformationPasses(), registerAllConversionPasses(), and circt::esi::registerESIPasses().
registerAllTranslations()
void circt::registerAllTranslations () inline
Definition at line 27 of file InitAllTranslations.h.
References circt::esi::registerESITranslations(), registerFIRRTLToVerilogTranslation(), circt::firrtl::registerFromFIRRTLTranslation(), circt::llhd::registerToVerilogTranslation(), and registerToVerilogTranslation().
registerFIRRTLToVerilogTranslation()
void circt::registerFIRRTLToVerilogTranslation ()
Register a translation for exporting FIRRTL, RTL, and SV.
Definition at line 2331 of file ExportVerilogFIRRTL.cpp.
References exportFIRRTLToVerilog().
Referenced by registerAllTranslations().
registerToVerilogTranslation()
void circt::registerToVerilogTranslation ()
Register a translation for exporting FIRRTL, RTL, and SV.
Definition at line 2139 of file ExportVerilog.cpp.
References exportVerilog().
Referenced by registerAllTranslations().