CIRCT: circt::rtl Namespace Reference
circt::rtl Namespace Reference
Classes
class CombinatorialVisitor
This helps visit Combinatorial nodes.
struct ModulePortInfo
This holds the name, type, direction of a module's ports.
class RTLDialect
class StmtVisitor
This helps visit Combinatorial nodes.
Enumerations
enum PortDirection { INPUT = 1, OUTPUT = 2, INOUT = 3 }
A RTL module ports direction.
Functions
FunctionType getModuleType (Operation *op)
void getModulePortInfo (Operation *op, SmallVectorImpl< ModulePortInfo > &results)
StringAttr getRTLNameAttr (ArrayRef< NamedAttribute > attrs)
bool isCombinatorial (Operation *op)
Return true if the specified operation is a combinatorial logic op.
bool isRTLIntegerType (mlir::Type type)
Return true if the specified type is a value RTL Integer type.
bool isRTLValueType (mlir::Type type)
Return true if the specified type can be used as an RTL value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
int64_t getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
bool hasRTLInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
bool operator== (const StructType::FieldInfo &a, const StructType::FieldInfo &b)
llvm::hash_code hash_value (const StructType::FieldInfo &fi)
Enumeration Type Documentation
PortDirection
enum circt::rtl::PortDirection
A RTL module ports direction.
Enumerator
INPUT
OUTPUT
INOUT
Definition at line 30 of file RTLOps.h.
Function Documentation
getBitWidth()
int64_t circt::rtl::getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
Does not reflect any encoding, padding, or storage scheme, just the bit (and wire width) of a statically-size type. Reflects the number of wires needed to transmit a value of this type. Returns -1 if the type is not known or cannot be statically computed.
Definition at line 68 of file RTLTypes.cpp.
References hasRTLInOutType().
Referenced by verifyRTLStructCastOp().
getModulePortInfo()
void circt::rtl::getModulePortInfo (Operation * op, SmallVectorImpl< ModulePortInfo > & results)
Definition at line 111 of file RTLOps.cpp.
References getArgAttrs(), getModuleType(), getRTLNameAttr(), INOUT, INPUT, and OUTPUT.
Referenced by circt::rtl::ModulePortInfo::isOutput(), and verifyInstanceOp().
getModuleType()
FunctionType circt::rtl::getModuleType (Operation * op)
Definition at line 97 of file RTLOps.cpp.
Referenced by getModulePortInfo(), circt::rtl::ModulePortInfo::isOutput(), and verifyOutputOp().
getRTLNameAttr()
StringAttr circt::rtl::getRTLNameAttr (ArrayRef< NamedAttribute > attrs)
Definition at line 102 of file RTLOps.cpp.
Referenced by getModulePortInfo(), circt::rtl::ModulePortInfo::isOutput(), parseFunctionResultList(), and printModuleSignature().
hash_value()
llvm::hash_code circt::rtl::hash_value (const StructType::FieldInfo & fi)
Definition at line 146 of file RTLTypes.cpp.
References parseRTLElementType(), print(), and printRTLElementType().
hasRTLInOutType()
bool circt::rtl::hasRTLInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
Unlike isRTLValueType, this is not conservative, it only returns false on known InOut types, rather than any unknown types.
Referenced by getBitWidth().
isCombinatorial()
bool circt::rtl::isCombinatorial (Operation * op)
Return true if the specified operation is a combinatorial logic op.
Definition at line 562 of file RTLOps.cpp.
References circt::rtl::CombinatorialVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchCombinatorialVisitor().
Referenced by circt::rtl::ModulePortInfo::isOutput(), and isVerilogExpression().
isRTLIntegerType()
bool circt::rtl::isRTLIntegerType (mlir::Type type)
Return true if the specified type is a value RTL Integer type.
This checks that it is a signless standard dialect type and that it isn't zero bits.
This checks that it is a signless standard dialect type, that it isn't zero bits.
Definition at line 34 of file RTLTypes.cpp.
References isRTLValueType().
isRTLValueType()
bool circt::rtl::isRTLValueType (mlir::Type type)
Return true if the specified type can be used as an RTL value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
Referenced by isRTLIntegerType().
operator==()
bool circt::rtl::operator== (const StructType::FieldInfo & a, const StructType::FieldInfo & b)
Definition at line 142 of file RTLTypes.cpp.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::getType(), and circt::firrtl::BundleType::BundleElement::operator!=().