CIRCT: circt::esi Namespace Reference
circt::esi Namespace Reference
Namespaces
capnp
cosim
Classes
class ESIDialect
Functions
void registerESIPasses ()
void registerESITranslations ()
std::unique_ptr< OperationPass< ModuleOp > > createESIPhysicalLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESIPortLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > createESItoRTLPass ()
Function Documentation
createESIPhysicalLoweringPass()
std::unique_ptr<OperationPass<ModuleOp> > circt::esi::createESIPhysicalLoweringPass ()
Definition at line 941 of file ESIPasses.cpp.
createESIPortLoweringPass()
std::unique_ptr<OperationPass<ModuleOp> > circt::esi::createESIPortLoweringPass ()
Definition at line 944 of file ESIPasses.cpp.
createESItoRTLPass()
std::unique_ptr<OperationPass<ModuleOp> > circt::esi::createESItoRTLPass ()
Definition at line 947 of file ESIPasses.cpp.
registerESIPasses()
void circt::esi::registerESIPasses ()
Definition at line 959 of file ESIPasses.cpp.
Referenced by circt::esi::ESIDialect::getDialectNamespace(), and circt::registerAllPasses().
registerESITranslations()
void circt::esi::registerESITranslations ()
Definition at line 168 of file ESITranslations.cpp.
Referenced by circt::esi::ESIDialect::getDialectNamespace(), and circt::registerAllTranslations().