CIRCT: lib/Dialect/RTL/RTLFolds.cpp File Reference
RTLFolds.cpp File Reference
#include "circt/Dialect/RTL/RTLOps.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
Functions
static Attribute getIntAttr (const APInt &value, MLIRContext *context)
static ConstantIntMatcher m_RConstant (APInt &value)
template<typename Op >
static bool tryFlatteningOperands (Op op, PatternRewriter &rewriter)
Flattens a single input in op if hasOneUse is true and it can be defined as an Op.
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>>
static Attribute constFoldVariadicOp (ArrayRef< Attribute > operands, const CalculationT &calculate)
static LogicalResult tryCanonicalizeConcat (ConcatOp op, PatternRewriter &rewriter)
static bool applyCmpPredicate (ICmpPredicate predicate, const APInt &lhs, const APInt &rhs)
static bool applyCmpPredicateToEqualOperands (ICmpPredicate predicate)
Function Documentation
applyCmpPredicate()
static bool applyCmpPredicate (ICmpPredicate predicate, const APInt & lhs, const APInt & rhs) static
Definition at line 756 of file RTLFolds.cpp.
Referenced by applyCmpPredicateToEqualOperands().
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (ICmpPredicate predicate) static
Definition at line 785 of file RTLFolds.cpp.
References applyCmpPredicate(), and m_RConstant().
constFoldVariadicOp()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>> static Attribute constFoldVariadicOp (ArrayRef< Attribute > operands, const CalculationT & calculate) static
Definition at line 172 of file RTLFolds.cpp.
References getIntAttr(), m_RConstant(), size(), and tryFlatteningOperands().
getIntAttr()
static Attribute getIntAttr (const APInt & value, MLIRContext * context) static
Definition at line 21 of file RTLFolds.cpp.
Referenced by constFoldVariadicOp(), and tryFlatteningOperands().
m_RConstant()
static ConstantIntMatcher m_RConstant (APInt & value) inline static
Definition at line 40 of file RTLFolds.cpp.
Referenced by applyCmpPredicateToEqualOperands(), and constFoldVariadicOp().
tryCanonicalizeConcat()
static LogicalResult tryCanonicalizeConcat (ConcatOp op, PatternRewriter & rewriter) static
Definition at line 609 of file RTLFolds.cpp.
References size().
tryFlatteningOperands()
template<typename Op > static bool tryFlatteningOperands (Op op, PatternRewriter & rewriter) static
Flattens a single input in op if hasOneUse is true and it can be defined as an Op.
Returns true if successful, and false otherwise.
Example: op(1, 2, op(3, 4), 5) -> op(1, 2, 3, 4, 5) // returns true
Definition at line 50 of file RTLFolds.cpp.
References getIntAttr(), and size().
Referenced by constFoldVariadicOp().