CIRCT: lib/Dialect/RTL/RTLOps.cpp File Reference
RTLOps.cpp File Reference
#include "circt/Dialect/RTL/RTLOps.h"
#include "circt/Dialect/RTL/RTLVisitors.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "circt/Dialect/RTL/RTL.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< ModulePortInfo > ports)
static ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs)
Parse a function result list.
static ParseResult parseModuleFunctionSignature (OpAsmParser &parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs)
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
static ParseResult parseRTLModuleOp (OpAsmParser &parser, OperationState &result, bool isExtModule=false)
static ParseResult parseRTLExternModuleOp (OpAsmParser &parser, OperationState &result)
FunctionType getRTLModuleOpType (Operation *op)
static void printModuleSignature (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes)
static void printRTLModuleOp (OpAsmPrinter &p, Operation *op)
static void print (OpAsmPrinter &p, RTLExternModuleOp op)
static void print (OpAsmPrinter &p, RTLModuleOp op)
static LogicalResult verifyInstanceOp (InstanceOp op)
static LogicalResult verifyOutputOp (OutputOp *op)
Verify that the num of operands and types fit the declared results.
static LogicalResult verifyConstantOp (ConstantOp constant)
static LogicalResult verifySExtOp (SExtOp op)
static LogicalResult verifyExtractOp (ExtractOp op)
static ParseResult parseSliceTypes (OpAsmParser &p, Type &srcType, Type &idxType)
static void printSliceTypes (OpAsmPrinter &p, Operation *, Type srcType, Type idxType)
static ParseResult parseArrayCreateOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ArrayCreateOp op)
static LogicalResult verifyUTVariadicRTLOp (Operation *op)
static ParseResult parseStructCreateOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, rtl::StructCreateOp op)
static ParseResult parseStructExplodeOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, rtl::StructExplodeOp op)
static ParseResult parseStructExtractOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, rtl::StructExtractOp op)
static ParseResult parseStructInjectOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, rtl::StructInjectOp op)
static ParseResult parseImplicitSSAName (OpAsmParser &parser, NamedAttrList &resultAttrs)
static void printImplicitSSAName (OpAsmPrinter &p, Operation *op, DictionaryAttr attr)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 949 of file RTLOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< ModulePortInfo > ports) static
Definition at line 25 of file RTLOps.cpp.
getRTLModuleOpType()
FunctionType getRTLModuleOpType (Operation * op)
Definition at line 291 of file RTLOps.cpp.
Referenced by printRTLModuleOp().
parseArrayCreateOp()
static ParseResult parseArrayCreateOp (OpAsmParser & parser, OperationState & result) static
Definition at line 676 of file RTLOps.cpp.
parseFunctionResultList()
static ParseResult parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs) static
Parse a function result list.
function-result-list ::= function-result-list-parens function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= (percent-identifier :) type attribute-dict?
Definition at line 147 of file RTLOps.cpp.
References circt::rtl::getRTLNameAttr().
Referenced by parseModuleFunctionSignature().
parseImplicitSSAName()
static ParseResult parseImplicitSSAName (OpAsmParser & parser, NamedAttrList & resultAttrs) static
Definition at line 895 of file RTLOps.cpp.
References isdigit.
parseModuleFunctionSignature()
static ParseResult parseModuleFunctionSignature (OpAsmParser & parser, bool allowVariadic, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs) static
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
Definition at line 188 of file RTLOps.cpp.
References parseFunctionResultList().
Referenced by parseRTLModuleOp().
parseRTLExternModuleOp()
static ParseResult parseRTLExternModuleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 286 of file RTLOps.cpp.
References parseRTLModuleOp().
parseRTLModuleOp()
static ParseResult parseRTLModuleOp (OpAsmParser & parser, OperationState & result, bool isExtModule = false) static
Definition at line 203 of file RTLOps.cpp.
References isdigit, and parseModuleFunctionSignature().
Referenced by parseRTLExternModuleOp().
parseSliceTypes()
static ParseResult parseSliceTypes (OpAsmParser & p, Type & srcType, Type & idxType) static
Definition at line 650 of file RTLOps.cpp.
parseStructCreateOp()
static ParseResult parseStructCreateOp (OpAsmParser & parser, OperationState & result) static
Definition at line 744 of file RTLOps.cpp.
parseStructExplodeOp()
static ParseResult parseStructExplodeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 777 of file RTLOps.cpp.
parseStructExtractOp()
static ParseResult parseStructExtractOp (OpAsmParser & parser, OperationState & result) static
Definition at line 807 of file RTLOps.cpp.
parseStructInjectOp()
static ParseResult parseStructInjectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 844 of file RTLOps.cpp.
print() [1/7]
static void print (OpAsmPrinter & p, RTLExternModuleOp op) static
Definition at line 386 of file RTLOps.cpp.
References printRTLModuleOp().
print() [2/7]
static void print (OpAsmPrinter & p, RTLModuleOp op) static
Definition at line 390 of file RTLOps.cpp.
References printRTLModuleOp().
print() [3/7]
static void print (OpAsmPrinter & p, ArrayCreateOp op) static
Definition at line 699 of file RTLOps.cpp.
print() [4/7]
static void print (OpAsmPrinter & printer, rtl::StructCreateOp op) static
Definition at line 765 of file RTLOps.cpp.
print() [5/7]
static void print (OpAsmPrinter & printer, rtl::StructExplodeOp op) static
Definition at line 796 of file RTLOps.cpp.
print() [6/7]
static void print (OpAsmPrinter & printer, rtl::StructExtractOp op) static
Definition at line 832 of file RTLOps.cpp.
print() [7/7]
static void print (OpAsmPrinter & printer, rtl::StructInjectOp op) static
Definition at line 872 of file RTLOps.cpp.
printImplicitSSAName()
static void printImplicitSSAName (OpAsmPrinter & p, Operation * op, DictionaryAttr attr) static
Definition at line 922 of file RTLOps.cpp.
printModuleSignature()
static void printModuleSignature (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes) static
Definition at line 296 of file RTLOps.cpp.
References getArgAttrs(), and circt::rtl::getRTLNameAttr().
Referenced by printRTLModuleOp().
printRTLModuleOp()
static void printRTLModuleOp (OpAsmPrinter & p, Operation * op) static
Definition at line 368 of file RTLOps.cpp.
References getRTLModuleOpType(), and printModuleSignature().
Referenced by print().
printSliceTypes()
static void printSliceTypes (OpAsmPrinter & p, Operation * , Type srcType, Type idxType) static
Definition at line 661 of file RTLOps.cpp.
References size().
verifyConstantOp()
static LogicalResult verifyConstantOp (ConstantOp constant) static
Definition at line 576 of file RTLOps.cpp.
verifyExtractOp()
static LogicalResult verifyExtractOp (ExtractOp op) static
Definition at line 641 of file RTLOps.cpp.
verifyInstanceOp()
static LogicalResult verifyInstanceOp (InstanceOp op) static
Definition at line 414 of file RTLOps.cpp.
References circt::rtl::getModulePortInfo().
verifyOutputOp()
static LogicalResult verifyOutputOp (OutputOp * op) static
Verify that the num of operands and types fit the declared results.
Definition at line 492 of file RTLOps.cpp.
References circt::rtl::getModuleType().
verifySExtOp()
static LogicalResult verifySExtOp (SExtOp op) static
Definition at line 625 of file RTLOps.cpp.
verifyUTVariadicRTLOp()
static LogicalResult verifyUTVariadicRTLOp (Operation * op) static
Definition at line 720 of file RTLOps.cpp.