CIRCT: lib/Dialect/ESI/capnp/Schema.cpp File Reference
Schema.cpp File Reference
#include "ESICapnp.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/RTL/RTLDialect.h"
#include "circt/Dialect/RTL/RTLOps.h"
#include "circt/Dialect/RTL/RTLTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "capnp/schema-parser.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Format.h"
#include <string>
Classes
struct circt::esi::capnp::detail::TypeSchemaImpl
Actual implementation of TypeSchema to keep all the details out of the header.
Namespaces
circt
circt::esi
circt::esi::capnp
circt::esi::capnp::detail
Functions
static llvm::raw_ostream & emitId (llvm::raw_ostream &os, int64_t id)
Emit an ID in capnp format.
static size_t bits (::capnp::schema::Type::Reader type)
Return the number of bits used by a Capnp primitive type.
static bool isSupported (Type type)
Returns true if the type is currently supported.
static int64_t size (rtl::ArrayType mType, capnp::schema::Field::Reader cField)
Returns the expected size of an array (capnp list) in 64-bit words.
static int64_t size (capnp::schema::Node::Struct::Reader cStruct, ArrayRef< Type > mFields)
Compute the size of a capnp struct, in 64-bit words.
static void emitName (Type type, llvm::raw_ostream &os)
Write a valid Capnp name for 'type'.
static void emitCapnpType (Type type, IndentingOStream &os)
Write a valid Capnp type.
static GasketComponent decodeList (rtl::ArrayType type, capnp::schema::Field::Reader field, Slice ptrSection, AssertBuilder &asserts)
Construct the proper operations to decode a capnp list.
static GasketComponent decodeField (Type type, capnp::schema::Field::Reader field, Slice dataSection, Slice ptrSection, AssertBuilder &asserts)
Construct the proper operations to convert a capnp field to 'type'.
Function Documentation
bits()
static size_t bits (::capnp::schema::Type::Reader type) static
Return the number of bits used by a Capnp primitive type.
Definition at line 121 of file Schema.cpp.
Referenced by decodeField(), decodeList(), and size().
decodeField()
static GasketComponent decodeField (Type type, capnp::schema::Field::Reader field, Slice dataSection, Slice ptrSection, AssertBuilder & asserts) static
Construct the proper operations to convert a capnp field to 'type'.
Definition at line 713 of file Schema.cpp.
References bits(), decodeList(), and circt::esi::capnp::detail::TypeSchemaImpl::type.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::buildDecoder().
decodeList()
static GasketComponent decodeList (rtl::ArrayType type, capnp::schema::Field::Reader field, Slice ptrSection, AssertBuilder & asserts) static
Construct the proper operations to decode a capnp list.
This only works for arrays of ints or bools. Will need to be updated for structs and lists of lists.
Definition at line 625 of file Schema.cpp.
References bits(), circt::esi::capnp::detail::TypeSchemaImpl::name(), and circt::esi::capnp::detail::TypeSchemaImpl::type.
Referenced by decodeField().
emitCapnpType()
static void emitCapnpType (Type type, IndentingOStream & os) static
Write a valid Capnp type.
Definition at line 308 of file Schema.cpp.
References circt::esi::capnp::detail::TypeSchemaImpl::type.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::write().
emitId()
static llvm::raw_ostream& emitId (llvm::raw_ostream & os, int64_t id) static
Emit an ID in capnp format.
Definition at line 62 of file Schema.cpp.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::getSchema(), and circt::esi::capnp::detail::TypeSchemaImpl::writeMetadata().
emitName()
static void emitName (Type type, llvm::raw_ostream & os) static
Write a valid Capnp name for 'type'.
Definition at line 277 of file Schema.cpp.
References circt::esi::capnp::detail::TypeSchemaImpl::type.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::name().
isSupported()
static bool isSupported (Type type) static
Returns true if the type is currently supported.
Definition at line 223 of file Schema.cpp.
References circt::esi::capnp::detail::TypeSchemaImpl::isSupported(), and circt::esi::capnp::detail::TypeSchemaImpl::type.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::getType(), and circt::esi::capnp::detail::TypeSchemaImpl::isSupported().
size() [1/2]
static int64_t size (rtl::ArrayType mType, capnp::schema::Field::Reader cField) static
Returns the expected size of an array (capnp list) in 64-bit words.
Definition at line 235 of file Schema.cpp.
References bits().
Referenced by constFoldVariadicOp(), convertTupleType(), circt::esi::capnp::detail::TypeSchemaImpl::getType(), isExpressionEmittedInline(), circt::esi::cosim::EndpointRegistry::operator[](), printArraySubscripts(), printSliceTypes(), circt::esi::capnp::detail::TypeSchemaImpl::size(), size(), tryCanonicalizeConcat(), and tryFlatteningOperands().
size() [2/2]
static int64_t size (capnp::schema::Node::Struct::Reader cStruct, ArrayRef< Type > mFields) static
Compute the size of a capnp struct, in 64-bit words.
Definition at line 245 of file Schema.cpp.
References circt::esi::capnp::detail::TypeSchemaImpl::size(), and size().