CIRCT: FuncOpLowering Struct Reference
FuncOpLowering Struct Reference
Public Member Functions
LogicalResult match (Operation *op) const override
void rewrite (mlir::FuncOp funcOp, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const override
Detailed Description
Definition at line 1405 of file StandardToHandshake.cpp.
Member Function Documentation
match()
LogicalResult FuncOpLowering::match (Operation * op) const inline override
Definition at line 1407 of file StandardToHandshake.cpp.
rewrite()
void FuncOpLowering::rewrite (mlir::FuncOp funcOp, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline override
Definition at line 1409 of file StandardToHandshake.cpp.
References addBranchOps(), addForkOps(), addMergeOps(), addSinkOps(), checkDataflowConversion(), connectConstantsToControl(), connectToMemory(), dotPrint(), getStartOp(), removeBasicBlocks(), replaceCallOps(), replaceMemoryOps(), rewriteAffineFor(), and setControlOnlyPath().
The documentation for this struct was generated from the following file:
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp