CIRCT: circt::rtl::ModulePortInfo Struct Reference
circt::rtl::ModulePortInfo Struct Reference
This holds the name, type, direction of a module's ports.
#include <RTLOps.h>
Public Member Functions
StringRef getName () const
bool isOutput () const
Public Attributes
StringAttr name
PortDirection direction
Type type
size_t argNum = ~0U
Detailed Description
This holds the name, type, direction of a module's ports.
Definition at line 37 of file RTLOps.h.
Member Function Documentation
getName()
StringRef circt::rtl::ModulePortInfo::getName () const inline
Definition at line 44 of file RTLOps.h.
isOutput()
bool circt::rtl::ModulePortInfo::isOutput () const inline
Definition at line 45 of file RTLOps.h.
References circt::rtl::getModulePortInfo(), circt::rtl::getModuleType(), circt::rtl::getRTLNameAttr(), circt::rtl::isCombinatorial(), and circt::rtl::OUTPUT.
Member Data Documentation
argNum
size_t circt::rtl::ModulePortInfo::argNum = ~0U
Definition at line 41 of file RTLOps.h.
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass().
direction
PortDirection circt::rtl::ModulePortInfo::direction
Definition at line 39 of file RTLOps.h.
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass().
name
StringAttr circt::rtl::ModulePortInfo::name
Definition at line 38 of file RTLOps.h.
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass().
type
Type circt::rtl::ModulePortInfo::type
Definition at line 40 of file RTLOps.h.
Referenced by circt::firrtl::createLowerFIRRTLToRTLModulePass().
The documentation for this struct was generated from the following file:
include/circt/Dialect/RTL/RTLOps.h